CREATE USER ncslkuser IDENTIFIED BY ncslkuser
DEFAULT TABLESPACE NCS_DB
TEMPORARY TABLESPACE NCS_DB_TEMP
PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT TO ncslkuser;
GRANT RESOURCE TO ncslkuser;
GRANT SELECT ANY TABLE TO ncs;
