({
	"dateFormatItem-yM": "M.yyyy", 
	"dateFormatItem-MMMEd": "E d MMM", 
	"eraNames": [
		"p.e.r.", 
		"n.e.r."
	], 
	"days-standAlone-wide": [
		"e diel", 
		"e hënë", 
		"e martë", 
		"e mërkurë", 
		"e enjte", 
		"e premte", 
		"e shtunë"
	], 
	"dateFormatItem-MMM": "LLL", 
	"patternChars": "GanjkHmsSEDFwWxhKzAeugXZvcL", 
	"months-standAlone-narrow": [
		"J", 
		"S", 
		"M", 
		"P", 
		"M", 
		"Q", 
		"K", 
		"G", 
		"S", 
		"T", 
		"N", 
		"D"
	], 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "h.mm.ss.a v", 
	"months-standAlone-abbr": [
		"Jan", 
		"Shk", 
		"Mar", 
		"Pri", 
		"Maj", 
		"Qer", 
		"Kor", 
		"Gsh", 
		"Sht", 
		"Tet", 
		"Nën", 
		"Dhj"
	], 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"days-standAlone-narrow": [
		"D", 
		"H", 
		"M", 
		"M", 
		"E", 
		"P", 
		"S"
	], 
	"eraAbbr": [
		"p.e.r.", 
		"n.e.r."
	], 
	"dateFormat-long": "dd MMMM yyyy", 
	"timeFormat-medium": "h:mm:ss.a", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "yyyy-MM-dd", 
	"dateFormatItem-yMMMM": "MMMM yyyy", 
	"dateFormatItem-ms": "mm:ss", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"months-standAlone-wide": [
		"janar", 
		"shkurt", 
		"mars", 
		"prill", 
		"maj", 
		"qershor", 
		"korrik", 
		"gusht", 
		"shtator", 
		"tetor", 
		"nëntor", 
		"dhjetor"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "h.mm.ss.a z", 
	"months-format-abbr": [
		"Jan", 
		"Shk", 
		"Mar", 
		"Pri", 
		"Maj", 
		"Qer", 
		"Kor", 
		"Gsh", 
		"Sht", 
		"Tet", 
		"Nën", 
		"Dhj"
	], 
	"timeFormat-short": "h.mm.a", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"days-format-abbr": [
		"Die", 
		"Hën", 
		"Mar", 
		"Mër", 
		"Enj", 
		"Pre", 
		"Sht"
	], 
	"pm": "MD", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"D", 
		"H", 
		"M", 
		"M", 
		"E", 
		"P", 
		"S"
	], 
	"dateFormatItem-MEd": "E, d.M", 
	"months-format-narrow": [
		"J", 
		"S", 
		"M", 
		"P", 
		"M", 
		"Q", 
		"K", 
		"G", 
		"S", 
		"T", 
		"N", 
		"D"
	], 
	"am": "PD", 
	"days-standAlone-abbr": [
		"Die", 
		"Hën", 
		"Mar", 
		"Mër", 
		"Enj", 
		"Pre", 
		"Sht"
	], 
	"dateFormat-short": "yy-MM-dd", 
	"dateFormatItem-yMMMEd": "d MMM yyyy", 
	"dateFormat-full": "EEEE, dd MMMM yyyy", 
	"dateFormatItem-Md": "M-d", 
	"dateFormatItem-yMEd": "EEE, d.M.yyyy", 
	"months-format-wide": [
		"janar", 
		"shkurt", 
		"mars", 
		"prill", 
		"maj", 
		"qershor", 
		"korrik", 
		"gusht", 
		"shtator", 
		"tetor", 
		"nëntor", 
		"dhjetor"
	], 
	"dateFormatItem-d": "d", 
	"days-format-wide": [
		"e diel", 
		"e hënë", 
		"e martë", 
		"e mërkurë", 
		"e enjte", 
		"e premte", 
		"e shtunë"
	], 
	"eraNarrow": [
		"p.e.r.", 
		"n.e.r."
	]
})