/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli Self Service Station",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Service Request Manager",
	About: "프로그램 정보",
	Help: "도움말",
	Logout: "로그아웃",
	Welcome: "시작",
	// Login widget
	LoginHeading: "Maximo 로그인",
	Username: "사용자 이름",
	Password: "암호",
	Login: "로그인",
	InvalidLogin: "사용자 이름 또는 암호가 올바르지 않습니다. 다시 시도하십시오.",
	NotAuthorized: "이 사용자에게는 애플리케이션을 사용할 권한이 없습니다.",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "선택한 행의 세부사항 표시",
	ApproveSelectedRequest: "선택된 요청 승인",
	RejectSelectedRequest: "선택된 요청 거부",
	ShowDetails: "세부사항 표시",
	Details:"세부사항",
	MyCatalogRequestHeading: "내 요청",
	MyApprovalHeading: "내 승인",	
	Refresh: "새로고침",
	// my catalog request grid column headings
	TotalCost: "총 비용",
	ChangeDate: "변경 날짜",
	RequestedBy: "요청자",
	Status: "상태",
	Quantity: "수량",
	UnitCost: "단가",
	Description: "설명",
	ItemNum: "요청 유형",
	RequestedFor: "요청 대상",
	ItemSetID: "품목 세트 ID",
	DateEntered: "입력 날짜",
	MRNum: "MR 번호",
	Priority: "우선순위",
	SiteID: "사이트 ID",
	MRLINEID: "MR 라인 ID",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "프로젝트",
	Name: "이름",
	ServiceOwner: "서비스 소유자",
	StatusDate: "상태 시간",
	DueDate: "만료 날짜",
	CreatedDate: "작성 날짜",
	StartDate: "목표 시작 날짜",
	OfferingDescription: "요청 설명",
	Approval: "승인",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "새 프로젝트 작성",
	CatalogOfferingPrompt: "서비스 카탈로그 오퍼링",
	CreateRequestStatus: "요청 제출 완료",
	CreateRequestButtonLabel: "확인",
	CancelButtonLabel: "취소",
	
	// Navigator widget
	Home: "홈",
	Back: "뒤로", 
	Forward: "앞으로",
	HomeBreadcrumb: "홈",
	Search: "검색",
	SearchResults: "검색 결과",
	Close: "닫기",
	IncidentsLabel: "티켓팅 도움말 및 지원",
	IncidentsDesc: "기존 자산 또는 서비스의 티켓 도움말을 엽니다.",
	RequestsLabel: "새 서비스 요청",
	RequestsDesc: "새 자산 또는 서비스를 요청합니다.",
	RecentsLabel: "자주하는 요청",
	RecentsDesc: "가장 자주 요청하는 서비스에 빠르게 액세스합니다.",
	None: "없음",
	NA: "해당안됨",
	//branch in navigator tree
	Directory: "디렉토리",
	//leaf in navigator tree
	Panel: "패널",
	// DateRange Widget
	DurationLabel: "지속 기간",
	MonthsLabel: "개월",
	WeeksLabel: "주",
	DaysLabel: "일",
	ForeverLabel: "계속",
	StartDateLabel: "시작 날짜",
	EndDateLabel: "종료 날짜",
	StartTime: "시작 시간",
	EndTime: "종료 시간",
	UntilLabel: "기한",
	InvalidDurationMessage: "지속 기간은 0보다 커야 합니다.",
	InvalidDateMessage: "날짜가 올바르지 않습니다.",
	DateEarlyMessage: "허용되는 가장 빠른 날짜인 ${0}보다 빠릅니다.",
	DateLateMessage: "허용되는 가장 늦은 날짜인 ${0}보다 늦습니다.",
	MissingDateMessage: "이 날짜는 필수입니다.",

	Loading: "로드 중...",
	RecentActivity: "최근 활동",
	NoRecentActivity: "최근 활동 없음",
	ManageRequests: "요청 관리",
	ManageRequestsLink: "요청 관리...",
	ManageApprovalsLink: "승인 관리...",
	ManageApprovals: "승인 관리",

	//General
	OK : "확인",
	Cancel : "취소",
	Select: "선택",
	Total: "총계",
	TotalLabel: "전체: ",
	
	// error messages
	MemChunkError: "%1 메모리는 %2MB의 배수여야 합니다.",
	CTJZH2301I: "CTJZH2301I: 일치사항이 없습니다.",
	CTJZH2302I: "CTJZH2302I: 정상적으로 로그인되었습니다.",
	CTJZH2303I: "CTJZH2303I: 로그인되지 않았습니다.",
	CTJZH2304I: "CTJZH2304I: 가상 서버를 선택해야 합니다.",
	
	CTJZH2301W: "CTJZH2301W: 예약을 위해 사용할 수 있는 시작 날짜 목록을 검색하지 못했습니다.",
	CTJZH2302W: "CTJZH2302W: 선택된 서버에 이미 이미지가 있습니다. 새 이미지가 기존 이미지를 대체합니다.",
	
	CTJZH2301E: "CTJZH2301E: 이 요청에 대한 입력 양식을 작성하는 중에 오류가 발생했습니다.",
	CTJZH2302E: "CTJZH2302E: 이 요청의 세부사항을 검색하는 중에 오류가 발생했습니다.",
	CTJZH2303E: "CTJZH2303E: 요청을 작성하려면 로그인해야 합니다.",
	CTJZH2304E: "CTJZH2304E: 이 요청을 작성하는 중에 오류가 발생했습니다.",
	CTJZH2305E: "CTJZH2305E: 입력 필드에 유효하지 않은 값이 있습니다.<br>계속하기 전에 이 오류를 수정해야 합니다.",
	CTJZH2306E: "CTJZH2306E: 이 요청을 작성하는 중에 시스템이 오류를 보고했습니다.",
	CTJZH2307E: "CTJZH2307E: 로그인하는 중에 오류가 발생했습니다.",
	CTJZH2308E: "CTJZH2308E: 죄송하지만, 이 요청을 작성하는 것은 현재 지원되지 않습니다.",
	CTJZH2309E: "CTJZH2309E: 내부 오류가 발생하여 계속 진행할 수 없습니다.",
	CTJZH2310E: "CTJZH2310E: 프로젝트의 세부사항을 표시하지 못하여, 프로젝트 ID를 찾을 수 없습니다.",
	CTJZH2311E: "CTJZH2311E: 내부 오류가 발생하여 프로젝트의 세부사항을 표시할 수 없습니다.",
	CTJZH2312E: "CTJZH2312E: 프로젝트의 세부사항을 검색하는 중에 오류가 발생했습니다.",
	CTJZH2313E: "CTJZH2313E: 서비스 요청 목록을 검색하지 못했습니다.",
	CTJZH2314E: "CTJZH2314E: 이 프로젝트의 세부사항을 검색하는 중에 오류가 발생했습니다.",
	CTJZH2315E: "CTJZH2315E: 프로젝트 목록을 검색하지 못했습니다.",
	CTJZH2316E: "CTJZH2316E: 일부 메시지를 표시하지만 메시지에 널(Null)이거나 정의되지 않았거나 비어 있는 코드가 있거나 유효하지 않은 유형이있습니다.",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W: 암호 확인이 일치하지 않습니다!", 
	CTJZH2318W: "CTJZH2318W: 최대 5개 팀을 선택할 수 있습니다!",
	CTJZH2319W: "CTJZH2319W: 사용자 이름이 이미 존재합니다!",
	CTJZH2320W: "CTJZH2320W: 최대 15명의 사용자를 선택할 수 있습니다!",
	CTJZH2321I: "CTJZH2321I: 이 요청에 대해 표시할 세부사항이 없습니다.",
	CTJZH2322W: "CTJZH2322W: 암호는 공백 문자로 시작하거나 끝날 수 없습니다.", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E: 선택한 요청을 처리하지 못했습니다.",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "팀",
	UserTeams: "사용자 팀",
	
	//UserStatus: "Activate user account",
	LOGINID: "로그인 ID",
	AccountLegend: "계정 설정",
	PersonalInfoLegend: "개인 정보",
	RegionalSettLegend: "지역 설정",
	FirstName: "이름",
	LastName: "성",
	DisplayName: "표시 이름",
	Email: "전자우편",
	Telephone: "전화",
	Address: "주소",
	City: "시/군",
	State: "상태",
	Country: "국가",
	AccountStatus: "활성",
	EmptyString: "               ",
	UserList: "사용 가능한 사용자",
	UserID: "사용자 ID",
	Role: "역할",
	ConfirmPassword: "암호 확인",
	InvalidConfirmPassword: "암호가 일치하지 않습니다.",
	PressToAddTeam: "팀을 추가하려면 +를 누르십시오.",
	// Team Management
	TeamID: "ID",
	TeamName: "이름",
	TeamDescription: "설명",
	UserList: "사용 가능한 사용자",
	SelectedUserList: "선택한 사용자",
	TeamDetails: "팀 세부사항",
	
	//Project Details
	ProjectTitle: "프로젝트",
	ProjectDetails: "프로젝트 세부사항",
	ProjectDetailsImage: "",
	ProjectName: "프로젝트 이름",
	ProjectDescription: "프로젝트 설명",
	ProjectType: "프로젝트 유형",
	ProjectStartDate: "시작 날짜",
	ProjectEndDate: "종료 날짜",
	ProjectTeamAccess: "팀 액세스",
	ProjectsDropDownEmptyLabel: "프로젝트 선택",	
	
	//WCA Projects
	WCAProjectTitle: "WebSphere CloudBurst 프로젝트",
	WCAProjectDetails: "WebSphere CloudBurst 프로젝트 세부사항",
	WCAProjectPattern: "패턴 이름",
	WCAServerResourcesLegend: "자원",
	WCAServerVirtualCPU: "가상 CPU",
	WCAServerMemory: "주 메모리",
	WCAPatternSelection: "CloudBurst 패턴 선택",
	
	ServerGridName: "서버 이름",
	ServerGridOS: "운영 체제",
	ServerGridStatus: "상태",
	ServerGridMemory: "메모리(%)",
	ServerGridCPU: "CPU(%)",
	ServerGridDisk: "디스크(%)",
	ServerGridLastUpdate: "마지막 갱신 날짜",
	ServerGridHypervisor: "하이퍼바이저",
	WCAServerGridPart: "파트",
	ProjectRequestedServers: "요청된 서버",
	ProjectActiveServers: "활성 서버",
	
	ViewProjectGeneralLegend: "일반",
	ViewProjectName: "이름",
	ViewProjectDescription: "설명",
	ViewProjectServiceOwner: "서비스 소유자",
	ViewProjectType: "프로젝트 유형",
	ViewProjectStartDate: "시작 날짜",
	ViewProjectEndDate: "종료 날짜",
	ViewProjectTeamAccess: "팀 액세스",
	ViewProjectRequestedServer: "요청된 서버",
	ViewProjectActiveServers: "활성 서버",
	
	ViewProjectServersLegend: "서버",
	ViewProjectServersTitle: "서버",
	ViewProjectMasterImage: "마스터 이미지",
	ViewProjectCreateDate: "작성 날짜",
	ViewProjectCreatedBy: "작성자",
	ViewProjectHypervisor: "하이퍼바이저",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "가상",
	ViewProjectPhysical: "실제",
	ViewProjectMain: "주",
	ViewProjectSwap: "스왑",
	ViewProjectDisk: "디스크",
	ViewProjectLocal: "로컬",
	ViewProjectAdditionalSoftware: "추가 소프트웨어",
	ViewProjectMemory: "메모리",
	ViewProjectServersTotal: "전체: ",
	Yes: "예",
	No: "아니오",
	UserExist: "사용자가 이미 존재함",
	MaxTeamsExceed: "팀의 최대 길이 초과",
	PreviewCloseTitle: "섹션 닫기",
	PreviewOpenTitle: "섹션 열기",

	/* Service Request details */
	Application: "애플리케이션",
	CreatedOn: "작성 날짜",
	Date: "날짜",
	Details: "세부사항",
	From: "시작",
	Subject: "제목",
	Summary: "요약",
	To: "종료",
	ViewSRDetails: "요청 세부사항",
	ViewSRTitle: "서비스 요청 보기",
	ViewSRGeneral: "일반",
	ViewSRGenBanner: "이 태스크를 사용하여 서비스 요청을 승인하거나 거부할 수 있습니다.",
	ViewSRLastUpdate: "마지막 업데이트",
	ViewSRUpdatedBy: "업데이트 기준",
	ViewSRWorkLog: "작업 로그",
	ViewSRWorkBanner: "서비스 요청에 대한 작업 로그. 노트의 세부사항을 보려면 테이블 행을 선택하십시오.",
	ViewSRNoWorkl: "표시할 작업 로그 없음",
	ViewSRCommLog: "통신 로그",
	ViewSRCommBanner: "서비스 요청에 대한 통신 로그. 노트의 세부사항을 보려면 테이블 행을 선택하십시오.",
	ViewSRNoComml: "표시할 통신 로그 없음",
	
	/* Approve Request */
	AppRequestBannerTitle: "승인",
	AppRequestBannerDescription: "승인에서 사용자 입력을 기다리고 있습니다. 선택하시겠습니까?",
	RejectRequest: "이 요청을 거부함",
	ApproveRequest: "이 요청을 승인함",
	ApproveSummary: "요약",
	ApproveDetails: "세부사항",
	
	
	copyright: "License Material - Property of IBM Corp. &copy; IBM Corporation and other(s) 2009. IBM은 미국 또는 기타 국가에서 사용되는 IBM Corporation의 등록 상표입니다.",
	AboutCopyright: "Licensed Materials - Property of IBM Corp. &copy; Copyright IBM Corp. 2009. All Rights Reserved. US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contact with IBM Corp.",
	dummy_: ""
}

