
package com.ibm.siam.am.idp.mcc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Com3Service", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.6.69.4:8000/MatchCode?wsdl")
public class Com3Service
    extends Service
{

    private final static URL COM3SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ibm.siam.am.idp.mcc.Com3Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ibm.siam.am.idp.mcc.Com3Service.class.getResource(".");
            url = new URL(baseUrl, "http://10.6.69.4:8000/MatchCode?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.6.69.4:8000/MatchCode?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COM3SERVICE_WSDL_LOCATION = url;
    }

    public Com3Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Com3Service(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://tempuri.org/", "Com3Service"));
    }

    public Com3Service() {
        super(COM3SERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "Com3Service"));
    }

    /**
     * 
     * @return
     *     returns ICodeTrans
     */
    @WebEndpoint(name = "BasicHttpBinding_ICodeTrans")
    public ICodeTrans getBasicHttpBindingICodeTrans() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICodeTrans"), ICodeTrans.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICodeTrans
     */
    @WebEndpoint(name = "BasicHttpBinding_ICodeTrans")
    public ICodeTrans getBasicHttpBindingICodeTrans(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICodeTrans"), ICodeTrans.class, features);
    }

}
