
package com.ibm.siam.am.idp.mcc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICodeTrans", targetNamespace = "http://Hirsch.Match.Code")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICodeTrans {


    /**
     * 
     * @param n1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AskMatch2", action = "http://Hirsch.Match.Code/ICodeTrans/AskMatch2")
    @WebResult(name = "AskMatch2Result", targetNamespace = "http://Hirsch.Match.Code")
    @RequestWrapper(localName = "AskMatch2", targetNamespace = "http://Hirsch.Match.Code", className = "com.ibm.siam.am.idp.mcc.AskMatch2")
    @ResponseWrapper(localName = "AskMatch2Response", targetNamespace = "http://Hirsch.Match.Code", className = "com.ibm.siam.am.idp.mcc.AskMatch2Response")
    public String askMatch2(
        @WebParam(name = "n1", targetNamespace = "http://Hirsch.Match.Code")
        String n1);

}
