/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli Self Service Station",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Service Request Manager",
	About: "关于",
	Help: "帮助",
	Logout: "注销",
	Welcome: "欢迎",
	// Login widget
	LoginHeading: "Maximo 登录",
	Username: "用户名",
	Password: "密码",
	Login: "登录",
	InvalidLogin: "用户名或密码不正确。请再试。",
	NotAuthorized: "此用户无权使用该应用程序",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "显示所选行的详细信息",
	ApproveSelectedRequest: "批准选择的请求",
	RejectSelectedRequest: "拒绝选择的请求",
	ShowDetails: "显示详细信息",
	Details:"详细信息",
	MyCatalogRequestHeading: "我的请求",
	MyApprovalHeading: "我的批准",	
	Refresh: "刷新",
	// my catalog request grid column headings
	TotalCost: "成本总计",
	ChangeDate: "变更日期",
	RequestedBy: "申请人",
	Status: "状态",
	Quantity: "数量",
	UnitCost: "单位成本",
	Description: "描述",
	ItemNum: "请求类型",
	RequestedFor: "使用人",
	ItemSetID: "存库项目集标识",
	DateEntered: "输入日期",
	MRNum: "物料编号",
	Priority: "优先级",
	SiteID: "站点标识",
	MRLINEID: "MRLINE 标识",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "项目",
	Name: "名称",
	ServiceOwner: "服务所有者",
	StatusDate: "状态时间",
	DueDate: "到期日",
	CreatedDate: "已创建",
	StartDate: "目标开始",
	OfferingDescription: "申请描述",
	Approval: "核准",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "创建新请求",
	CatalogOfferingPrompt: "服务目录提供",
	CreateRequestStatus: "已成功提交请求",
	CreateRequestButtonLabel: "确定",
	CancelButtonLabel: "取消",
	
	// Navigator widget
	Home: "主页",
	Back: "返回", 
	Forward: "向前",
	HomeBreadcrumb: "主页",
	Search: "搜索",
	SearchResults: "搜索结果",
	Close: "关闭",
	IncidentsLabel: "开帮助凭单和支持",
	IncidentsDesc: "为现有资产或服务开帮助凭单。",
	RequestsLabel: "请求新服务",
	RequestsDesc: "开获取新资产或服务的请求。",
	RecentsLabel: "频繁请求",
	RecentsDesc: "易于访问请求最频繁的服务。",
	None: "无",
	NA: "N/A",
	//branch in navigator tree
	Directory: "目录",
	//leaf in navigator tree
	Panel: "面板",
	// DateRange Widget
	DurationLabel: "在此持续时间内",
	MonthsLabel: "月",
	WeeksLabel: "周",
	DaysLabel: "天数",
	ForeverLabel: "永远",
	StartDateLabel: "开始日期",
	EndDateLabel: "结束日期",
	StartTime: "开始时间",
	EndTime: "结束时间",
	UntilLabel: "直到此日期",
	InvalidDurationMessage: "持续时间必须大于 0",
	InvalidDateMessage: "这不是有效日期",
	DateEarlyMessage: "这在 ${0}（最早允许日期）前",
	DateLateMessage: "这在 ${0}（最晚允许日期）后",
	MissingDateMessage: "此日期是必需的",

	Loading: "正在装入...",
	RecentActivity: "最近活动",
	NoRecentActivity: "无最近活动",
	ManageRequests: "管理请求",
	ManageRequestsLink: "管理请求...",
	ManageApprovalsLink: "管理批准...",
	ManageApprovals: "管理批准",

	//General
	OK : "确定",
	Cancel : "取消",
	Select: "选择",
	Total: "总计",
	TotalLabel: "总计： ",
	
	// error messages
	MemChunkError: "%1 内存必须是 %2MB 的倍数",
	CTJZH2301I: "CTJZH2301I: 抱歉，找不到匹配项。",
	CTJZH2302I: "CTJZH2302I: 登录成功。",
	CTJZH2303I: "CTJZH2303I: 您未登录。",
	CTJZH2304I: "CTJZH2304I: 必须选择虚拟服务器",
	
	CTJZH2301W: "CTJZH2301W: 检索可用的预留开始日期的列表失败。",
	CTJZH2302W: "CTJZH2302W: 所选服务器已经有映像。新映像将替换现有映像。",
	
	CTJZH2301E: "CTJZH2301E: 创建此请求的输入表单时出错。",
	CTJZH2302E: "CTJZH2302E: 检索此请求的详细信息时出错。",
	CTJZH2303E: "CTJZH2303E: 必须登录才能创建请求。",
	CTJZH2304E: "CTJZH2304E: 创建此请求时出错。",
	CTJZH2305E: "CTJZH2305E: 您已在字段中输入了无效值。<br>您必须在继续前更正这些错误。",
	CTJZH2306E: "CTJZH2306E: 系统在创建此请求时报告了一个错误。",
	CTJZH2307E: "CTJZH2307E: 您登录时出错。",
	CTJZH2308E: "CTJZH2308E: 很抱歉，但当前不支持创建此请求。",
	CTJZH2309E: "CTJZH2309E: 发生内部错误，无法继续。",
	CTJZH2310E: "CTJZH2310E: 显示该项目的详细信息时失败，我无法找到项目标识。",
	CTJZH2311E: "CTJZH2311E: 发生内部错误，无法显示项目详细信息。",
	CTJZH2312E: "CTJZH2312E: 检索该项目的详细信息时出错。",
	CTJZH2313E: "CTJZH2313E: 检索服务请求列表时失败。",
	CTJZH2314E: "CTJZH2314E: 检索此项目详细信息时出错。",
	CTJZH2315E: "CTJZH2315E: 检索项目列表时失败。",
	CTJZH2316E: "CTJZH2316E: 应显示某条消息，但是它有空的或未定义的代码，或者类型无效。",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W: 确认密码不匹配！", 
	CTJZH2318W: "CTJZH2318W: 只允许选择最多 5 个团队！",
	CTJZH2319W: "CTJZH2319W: 用户名已经存在！",
	CTJZH2320W: "CTJZH2320W: 只允许选择最多 15 名用户！",
	CTJZH2321I: "CTJZH2321I: 对于此请求，无详细信息显示",
	CTJZH2322W: "CTJZH2322W: 密码的开头和结尾不可为空白字符", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E: 未能处理您选择的请求。",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "团队",
	UserTeams: "用户团队",
	
	//UserStatus: "Activate user account",
	LOGINID: "登录标识",
	AccountLegend: "帐户设置",
	PersonalInfoLegend: "个人信息",
	RegionalSettLegend: "区域设置",
	FirstName: "名",
	LastName: "姓",
	DisplayName: "显示姓名",
	Email: "电子邮件",
	Telephone: "电话",
	Address: "地址",
	City: "城市",
	State: "省/市/自治区",
	Country: "国家或地区",
	AccountStatus: "活动",
	EmptyString: "               ",
	UserList: "可用用户",
	UserID: "用户标识",
	Role: "角色",
	ConfirmPassword: "确认密码",
	InvalidConfirmPassword: "确认密码不匹配",
	PressToAddTeam: "按 + 添加团队",
	// Team Management
	TeamID: "标识",
	TeamName: "名称",
	TeamDescription: "描述",
	UserList: "可用用户",
	SelectedUserList: "所选用户",
	TeamDetails: "团队详细信息",
	
	//Project Details
	ProjectTitle: "项目",
	ProjectDetails: "项目详细信息",
	ProjectDetailsImage: "",
	ProjectName: "项目名称",
	ProjectDescription: "项目描述",
	ProjectType: "项目类型",
	ProjectStartDate: "开始日期",
	ProjectEndDate: "结束日期",
	ProjectTeamAccess: "团队访问",
	ProjectsDropDownEmptyLabel: "选择项目",	
	
	//WCA Projects
	WCAProjectTitle: "WebSphere CloudBurst 项目",
	WCAProjectDetails: "WebSphere CloudBurst 项目详细信息",
	WCAProjectPattern: "模式名称",
	WCAServerResourcesLegend: "资源",
	WCAServerVirtualCPU: "虚拟 CPU",
	WCAServerMemory: "主存储器",
	WCAPatternSelection: "选择 CloudBurst 模式",
	
	ServerGridName: "服务器名称",
	ServerGridOS: "操作系统",
	ServerGridStatus: "状态",
	ServerGridMemory: "内存（%）",
	ServerGridCPU: "CPU（%）",
	ServerGridDisk: "磁盘（%）",
	ServerGridLastUpdate: "上次更新",
	ServerGridHypervisor: "管理程序",
	WCAServerGridPart: "部件",
	ProjectRequestedServers: "所请求的服务器",
	ProjectActiveServers: "活动服务器",
	
	ViewProjectGeneralLegend: "常规",
	ViewProjectName: "名称",
	ViewProjectDescription: "描述",
	ViewProjectServiceOwner: "服务所有者",
	ViewProjectType: "项目类型",
	ViewProjectStartDate: "开始日期",
	ViewProjectEndDate: "结束日期",
	ViewProjectTeamAccess: "团队访问",
	ViewProjectRequestedServer: "所请求的服务器",
	ViewProjectActiveServers: "活动服务器",
	
	ViewProjectServersLegend: "服务器",
	ViewProjectServersTitle: "服务器",
	ViewProjectMasterImage: "主映像",
	ViewProjectCreateDate: "创建日期",
	ViewProjectCreatedBy: "创建人",
	ViewProjectHypervisor: "管理程序",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "虚拟",
	ViewProjectPhysical: "物理",
	ViewProjectMain: "主界面",
	ViewProjectSwap: "交换",
	ViewProjectDisk: "磁盘",
	ViewProjectLocal: "本地",
	ViewProjectAdditionalSoftware: "其他软件",
	ViewProjectMemory: "内存",
	ViewProjectServersTotal: "总计： ",
	Yes: "是",
	No: "否",
	UserExist: "用户已存在",
	MaxTeamsExceed: "超出团队的最大长度",
	PreviewCloseTitle: "关闭节",
	PreviewOpenTitle: "打开节",

	/* Service Request details */
	Application: "应用程序",
	CreatedOn: "创建日期",
	Date: "日期",
	Details: "详细信息",
	From: "自",
	Subject: "主题",
	Summary: "摘要",
	To: "到",
	ViewSRDetails: "请求详细信息",
	ViewSRTitle: "查看服务请求",
	ViewSRGeneral: "常规",
	ViewSRGenBanner: "此任务允许您批准或拒绝服务请求",
	ViewSRLastUpdate: "上次更新",
	ViewSRUpdatedBy: "更新者",
	ViewSRWorkLog: "工作日志",
	ViewSRWorkBanner: "该服务请求的工作日志。请选择表行查看该备注的详细信息。",
	ViewSRNoWorkl: "无工作日志显示",
	ViewSRCommLog: "通信日志",
	ViewSRCommBanner: "该服务请求的通信日志。请选择表行查看该备注的详细信息。",
	ViewSRNoComml: "无通信日志显示",
	
	/* Approve Request */
	AppRequestBannerTitle: "批准",
	AppRequestBannerDescription: "待批准项正在等待您的意见。您作何决定？",
	RejectRequest: "我拒绝此请求",
	ApproveRequest: "我批准此请求",
	ApproveSummary: "摘要",
	ApproveDetails: "详细信息",
	
	
	copyright: "License Material - Property of IBM Corp. &copy; IBM Coporation and other(s) 2009. IBM 是 IBM Corporation 在美国和/或其他国家或地区的注册商标。",
	AboutCopyright: "Licensed Materials - Property of IBM Corp. &copy; Copyright IBM Corp. 2009. All Rights Reserved. US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contact with IBM Corp.",
	dummy_: ""
}

