//////////////////////////////////////////////////////////////////
// IBM Confidential
// OCO Source Material
// 5724-W78
// (C) Copyright IBM Corp. 2009
// The source code for this program is not published or otherwise
// divested of its trade secrets, irrespective of what has been
// deposited with the U. S. Copyright Office.
//////////////////////////////////////////////////////////////////

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli Self Service Station",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Service Request Manager",
	About: "About",
	Help: "Help",
	Logout: "Logout",
	Welcome: "Welcome",
	// Login widget
	LoginHeading: "Maximo Login",
	Username: "User Name",
	Password: "Password",
	Login: "Login",
	InvalidLogin: "User Name or Password is incorrect. Please try again.",
	NotAuthorized: "You are not authorized to use this application",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "Show details of the selected row",
	ApproveSelectedRequest: "Approve selected request",
	RejectSelectedRequest: "Reject selected request",
	ShowDetails: "Show details",
	MyCatalogRequestHeading: "My Requests",
	MyApprovalHeading: "My Approvals",	
	Refresh: "Refresh",
	// my catalog request grid column headings
	TotalCost: "Total Cost",
	ChangeDate: "Change Date",
	RequestedBy: "Requested By",
	Status: "Status",
	Quantity: "Quantity",
	UnitCost: "Unit Cost",
	Description: "Description",
	ItemNum: "Request Type",
	RequestedFor: "Requested For",
	ItemSetID: "Item Set ID",
	DateEntered: "Date Entered",
	MRNum: "MRNUM",
	Priority: "Priority",
	SiteID: "Site ID",
	MRLINEID: "MRLINE ID",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "Projects",
	Name: "Name",
	ServiceOwner: "Service Owner",
	StatusDate: "Status Time",
	DueDate: "Due Date",
	CreatedDate: "Created",
	StartDate: "Target Start",
	OfferingDescription: "Request Description",
	Approval: "Approval",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "Create A New Request",
	CatalogOfferingPrompt: "Service Catalog Offering",
	CreateRequestStatus: "Request Submitted Successfully",
	CreateRequestButtonLabel: "OK",
	CancelButtonLabel: "Cancel",
	
	// Navigator widget
	Home: "Home",
	Back: "Back", 
	Forward: "Forward",
	HomeBreadcrumb: "Home",
	Search: "Search",
	SearchResults: "Search Results",
	Close: "Close",
	IncidentsLabel: "Help Ticketing and Support",
	IncidentsDesc: "Open a help ticket for an existing asset or service.",
	RequestsLabel: "Request a New Service",
	RequestsDesc: "Open a request to acquire a new asset or service.",
	RecentsLabel: "Frequent requests",
	RecentsDesc: "Easy access to the services you most often request.",
	None: "None",
	NA: "N/A",
	//branch in navigator tree
	Directory: "Directory",
	//leaf in navigator tree
	Panel: "Panel",
	// DateRange Widget
	DurationLabel: "For this duration",
	MonthsLabel: "Months",
	WeeksLabel: "Weeks",
	DaysLabel: "Days",
	ForeverLabel: "Indefinite",
	StartDateLabel: "Start Date",
	EndDateLabel: "End Date",
	StartTime: "Start Time",
	EndTime: "End Time",
	UntilLabel: "Until this date",
	InvalidDurationMessage: "Duration must be greater than 0",
	InvalidDateMessage: "This is not a valid date",
	DateEarlyMessage: "This date is before ${0}, the earliest permissible date",
	DateLateMessage: "This date is after ${0}, the latest permissible date",
	MissingDateMessage: "This date is required",

	Loading: "Loading...",
	RecentActivity: "Recent Activity",
	NoRecentActivity: "No recent activity",
	ManageRequests: "Manage Requests",
	ManageRequestsLink: "Manage Requests...",
	ManageApprovalsLink: "Manage Approvals...",
	ManageApprovals: "Manage Approvals",

	//General
	OK : "OK",
	Cancel : "Cancel",
	Select: "Select",
	Total: "Total",
	TotalLabel: "Total: ",
	
	// error messages
	MemChunkError: "%1 memory must be a multiple of %2 MB",

	CTJZH2301E: "CTJZH2301E: An error occured creating the input form for this request.",
	CTJZH2302E: "CTJZH2302E: An error occured retrieving this request's details.",
	CTJZH2303E: "CTJZH2303E: You must be logged in to create a request.",
	CTJZH2304I: "CTJZH2304I: You must choose a virtual server",
	CTJZH2305E: "CTJZH2305E: You have input fields with invalid values. You must correct these errors before continuing.",
	CTJZH2306E: "CTJZH2306E: The system reported an error in creating this request.",
	CTJZH2307E: "CTJZH2307E: An error occurred while logging you in.",
	CTJZH2308E: "CTJZH2308E: Sorry, but creating this request is currently not supported.",
	CTJZH2309E: "CTJZH2309E: Cannot proceed due to an internal error.",
	CTJZH2310E: "CTJZH2310E: Failed to display the project's details. Cannot find a project ID.",
	CTJZH2311E: "CTJZH2311E: Cannot display the project's details due to an internal error.",
	CTJZH2312E: "CTJZH2312E: An error has occurred retrieving the project's details.",
	CTJZH2313E: "CTJZH2313E: Failed to retrieve the list of service requests.",
	CTJZH2314E: "CTJZH2314E: An error occurred retrieving this project's details.",
	CTJZH2315E: "CTJZH2315E: Failed to retrieve the list of projects.",
	CTJZH2316E: "CTJZH2316E: Message to be displayed has null, undefined or empty code, or invalid type.",
	CTJZH2317E: "CTJZH2317E: Password confirmation does not match.", 
	CTJZH2318E: "CTJZH2318E: A maximum of 5 teams can be selected.",
	CTJZH2319E: "CTJZH2319E: Username already exists.",
	CTJZH2320E: "CTJZH2320E: A maximum of 15 users can be selected.",
	CTJZH2321I: "CTJZH2321I: No details to display for this request.",
	CTJZH2322E: "CTJZH2322E: Password cannot start or end with a space.", 
	CTJZH2324E: "CTJZH2324E: Username contains spaces.",	
	CTJZH2323E: "CTJZH2323E: This service request cannot be submitted because there are no resource pools of this type registered.", 
	CTJZH2325E: "CTJZH2325E: The request is no longer available.",
	CTJZH2328W: "CTJZH2328W: Deleting the user cannot be undone and the userid may never be reused", 
	CTJZH2329E: "CTJZH2329E: The specified userid belongs to a user that has been deleted and cannot be reused", 
	CTJZH2331E: "CTJZH2331E: Failed when processing your selected request.",
	CTJZH2332E: "CTJZH2332E: Recommended value of memory cannot be smaller than its minimum value.",
    CTJZH2333E: "CTJZH2333E: Recommended physical CPUs cannot be smaller than minimum physical CPU.",
	CTJZH2334E: "CTJZH2334E: A server error occured updating this new service request with the provided data",
	CTJZH2335E: "CTJZH2335E: An unrecoverable server error occured while creating this new service request",
	CTJZH2336E: "CTJZH2336E: Approval Details input exceeded max length of 50 characters.",	
	CTJZH2337E: "CTJZH2337E: Cannot create a new service request because you do not appear to be logged in",
	CTJZH2338E: "CTJZH2338E: A server error occured creating this new service request",
	CTJZH2339I: "CTJZH2339I: Sorry, but no matches were found.",
	CTJZH2340W: "CTJZH2340W: Failed retrieving the list of available start dates for your reservation.",
	CTJZH2341W: "CTJZH2341W: Selected server already has an image. The new image will replace the existing one.",
	CTJZH2342E: "CTJZH2342E: An error occurred creating this request.",
	CTJZH2343E: "CTJZH2343E: One of the recommended resources is smaller than the corresponding minimum resource.",
	CTJZH2345E: "CTJZH2345E: You cannot remove this team while it has active projects.",
	CTJZH2346E: "CTJZH2346E: Password must be at least 6 characters in length",
	CTJZH2347E: "CTJZH2347E: No servers with these parameters are available on these dates.",

	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "Team",
	UserTeams: "User Teams",
	
	//UserStatus: "Activate user account",
	LOGINID: "Login ID",
	AccountLegend: "Account Settings",
	PersonalInfoLegend: "Personal Information",
	RegionalSettLegend: "Regional Settings",
	FirstName: "First Name",
	LastName: "Last Name",
	DisplayName: "Display Name",
	Email: "E-Mail",
	Telephone: "Telephone",
	Address: "Address",
	City: "City",
	State: "State",
	Country: "Country",
	AccountStatus: "Active",
	EmptyString: "               ",
	UserList: "Available Users",
	UserID: "User ID",
	Role: "Role",
	ConfirmPassword: "Confirm Password",
	InvalidConfirmPassword: "Password confirmation does not match",
	PressToAddTeam: "Press + to add team",
	// Team Management
	TeamID: "ID",
	TeamName: "Name",
	TeamDescription: "Description",
	UserList: "Available Users",
	SelectedUserList: "Selected Users",
	TeamDetails: "Team Details",
	ProjectAccount: "Project Account",
	QuickFilter: "quick filter",
	TeamNameExists: "A team with the same name already exists.",
	//Project Details
	ProjectTitle: "Project",
	ProjectDetails: "Project Details",
	ProjectDetailsImage: "",
	ProjectName: "Project Name",
	ProjectDescription: "Project Description",
	ProjectType: "Project Type",
	ProjectStartDate: "Start Date",
	ProjectEndDate: "End Date",
	ProjectTeamAccess: "Team Access",
	ProjectsDropDownEmptyLabel: "Select a project",	
	
	//WCA Projects
	WCAProjectTitle: "WebSphere CloudBurst Project",
	WCAProjectDetails: "WebSphere CloudBurst Project Details",
	WCAProjectPattern: "Pattern Name",
	WCAServerResourcesLegend: "Resources",
	WCAServerVirtualCPU: "Virtual CPU",
	WCAServerMemory: "Main Memory",
	WCAPatternSelection: "Select a CloudBurst Pattern",
	
	ServerGridName: "Server Name",
	ServerGridOS: "Operating System",
	ServerGridStatus: "Status",
	ServerGridMemory: "Memory (%)",
	ServerGridCPU: "CPU (%)",
	ServerGridDisk: "Disk (%)",
	ServerGridTotalMemory: "Memory",
	ServerGridTotalCPU: "CPU",
	ServerGridTotalDisk: "Disk",
	ServerGridLastUpdate: "Last Update",
	ServerGridHypervisor: "Hypervisor",
	WCAServerGridPart: "Part",
	ProjectRequestedServers: "Requested Server(s)",
	ProjectActiveServers: "Active Server(s)",
	
	ViewProjectGeneralLegend: "General",
	ViewProjectName: "Name",
	ViewProjectDescription: "Description",
	ViewProjectServiceOwner: "Service Owner",
	ViewProjectType: "Project Type",
	ViewProjectStartDate: "Start Date",
	ViewProjectEndDate: "End Date",
	ViewProjectTeamAccess: "Team Access",
	ViewProjectRequestedServer: "Requested Servers",
	ViewProjectActiveServers: "Active Servers",
	
	ViewProjectServersLegend: "Servers",
	ViewProjectServersTitle: "Server",
	ViewProjectMasterImage: "Master Image",
	ViewProjectCreateDate: "Create Date",
	ViewProjectCreatedBy: "Created By",
	ViewProjectHypervisor: "Hypervisor",
	ViewProjectServerStatus: "Provisioning Status",
	ViewProjectServerStatusLastUpdate: "Last provisioning status update",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "Virtual",
	ViewProjectPhysical: "Physical",
	ViewProjectMain: "Main",
	ViewProjectSwap: "Swap",
	ViewProjectDisk: "Disk",
	ViewProjectLocal: "Local",
	ViewProjectAdditionalSoftware: "Additional Software",
	ViewProjectMemory: "Memory",
	ViewProjectServersTotal: "Total: ",
	Yes: "Yes",
	No: "No",
	UserExist: "User already exists",
	MaxTeamsExceed: "Exceeds maximum length for team",
	PreviewCloseTitle: "Close Section",
	PreviewOpenTitle: "Open Section",
	ProjectUsed: "The project name is already in use.",

	/* Service Request details */
	Application: "Application",
	CreatedOn: "Created on",
	Date: "Date",
	Details: "Details",
	From: "From",
	Subject: "Subject",
	Summary: "Summary",
	FailedStatus: "Failed",
	To: "To",
	ViewSRDetails: "Request Details",
	ViewSRTitle: "View Service Request",
	ViewSRGeneral: "General",
	ViewSRGenBannerApproval: "This task allows you to approve or reject a service request",
	ViewSRGenBannerNoApproval: "This task displays the details of the service request",
	ViewSRLastUpdate: "Last update",
	ViewSRUpdatedBy: "Updated by",
	ViewSRWorkLog: "Work Log",
	ViewSRWorkBanner: "Work log for the service request. Select the table row to view the details of the note.",
	ViewSRNoWorkl: "No work log to display",
	ViewSRCommLog: "Communication Log",
	ViewSRCommBanner: "Communication log for the service request. Select the table row to view the details of the note.",
	ViewSRNoComml: "No communication log to display",
	
	/* ITM Agent Statuses */
	noAgentState: "No Monitor",
	onlineState: "Monitor online",
	offlineState: "Monitor offline",
	toobusyState: "Monitor too busy to respond",
	notconfiguredState: "Monitor not configured",
	
	/* Approve Request */
	AppRequestBannerTitle: "Approval",
	AppRequestBannerDescription: "An approval is waiting for your input. How do you vote?",
	RejectRequest: "I reject this request",
	ApproveRequest: "I approve this request",
	ApproveSummary: "Summary",
	ApproveDetails: "Details",
	
	ContextButtonSetLabelCreate: "Create",
	
	copyright: "License Material - Property of IBM Corp. &copy; IBM Corporation and other(s) 2009. IBM is a registered trademark of the IBM Corporation in the United States, other countries, or both.",
	AboutCopyright: "Licensed Materials - Property of IBM Corp. &copy; Copyright IBM Corp. 2009. All Rights Reserved. US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contact with IBM Corp.",
	dummy_: ""
}
