({
	"field-dayperiod": "Частина доби", 
	"field-minute": "Хвилина", 
	"eraNames": [
		"до нашої ери", 
		"нашої ери"
	], 
	"dateFormatItem-MMMEd": "E, d MMM", 
	"field-weekday": "День тижня", 
	"dateFormatItem-MMdd": "dd.MM", 
	"days-standAlone-wide": [
		"Неділя", 
		"Понеділок", 
		"Вівторок", 
		"Середа", 
		"Четвер", 
		"Пʼятниця", 
		"Субота"
	], 
	"dateFormatItem-MMM": "LLL", 
	"patternChars": "GanjkHmsSEDFwWxhKzAeugXZvcL", 
	"months-standAlone-narrow": [
		"С", 
		"Л", 
		"Б", 
		"К", 
		"Т", 
		"Ч", 
		"Л", 
		"С", 
		"В", 
		"Ж", 
		"Л", 
		"Г"
	], 
	"field-era": "Ера", 
	"field-hour": "Година", 
	"quarters-standAlone-abbr": [
		"I кв.", 
		"II кв.", 
		"III кв.", 
		"IV кв."
	], 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "HH:mm:ss v", 
	"months-standAlone-abbr": [
		"Січ", 
		"Лют", 
		"Бер", 
		"Кві", 
		"Тра", 
		"Чер", 
		"Лип", 
		"Сер", 
		"Вер", 
		"Жов", 
		"Лис", 
		"Гру"
	], 
	"dateFormatItem-yMMM": "LLL yyyy", 
	"days-standAlone-narrow": [
		"Н", 
		"П", 
		"В", 
		"С", 
		"Ч", 
		"П", 
		"С"
	], 
	"eraAbbr": [
		"до н.е.", 
		"н.е."
	], 
	"dateFormatItem-yyyyMMMM": "LLLL yyyy", 
	"dateFormat-long": "d MMMM yyyy 'р'.", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Зона", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormatItem-yyMM": "MM.yy", 
	"dateFormat-medium": "d MMM yyyy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"I квартал", 
		"II квартал", 
		"III квартал", 
		"IV квартал"
	], 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-yMMMM": "LLLL yyyy", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Рік", 
	"dateFormatItem-yyyyQQQQ": "QQQQ yyyy 'р'.", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"dateFormatItem-HHmmss": "HH:mm:ss", 
	"months-standAlone-wide": [
		"Січень", 
		"Лютий", 
		"Березень", 
		"Квітень", 
		"Травень", 
		"Червень", 
		"Липень", 
		"Серпень", 
		"Вересень", 
		"Жовтень", 
		"Листопад", 
		"Грудень"
	], 
	"field-week": "Тиждень", 
	"dateFormatItem-MMMMEd": "E, d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-HHmm": "HH:mm", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"січ.", 
		"лют.", 
		"бер.", 
		"квіт.", 
		"трав.", 
		"черв.", 
		"лип.", 
		"серп.", 
		"вер.", 
		"жовт.", 
		"лист.", 
		"груд."
	], 
	"field-month": "Місяць", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"I кв.", 
		"II кв.", 
		"III кв.", 
		"IV кв."
	], 
	"days-format-abbr": [
		"Нд", 
		"Пн", 
		"Вт", 
		"Ср", 
		"Чт", 
		"Пт", 
		"Сб"
	], 
	"pm": "пп", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"Н", 
		"П", 
		"В", 
		"С", 
		"Ч", 
		"П", 
		"С"
	], 
	"field-second": "Секунда", 
	"field-day": "День", 
	"months-format-narrow": [
		"С", 
		"Л", 
		"Б", 
		"К", 
		"Т", 
		"Ч", 
		"Л", 
		"С", 
		"В", 
		"Ж", 
		"Л", 
		"Г"
	], 
	"am": "дп", 
	"days-standAlone-abbr": [
		"Нд", 
		"Пн", 
		"Вт", 
		"Ср", 
		"Чт", 
		"Пт", 
		"Сб"
	], 
	"dateFormat-short": "dd.MM.yy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM yyyy", 
	"dateFormat-full": "EEEE, d MMMM yyyy 'р'.", 
	"months-format-wide": [
		"січня", 
		"лютого", 
		"березня", 
		"квітня", 
		"травня", 
		"червня", 
		"липня", 
		"серпня", 
		"вересня", 
		"жовтня", 
		"листопада", 
		"грудня"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"I квартал", 
		"II квартал", 
		"III квартал", 
		"IV квартал"
	], 
	"days-format-wide": [
		"Неділя", 
		"Понеділок", 
		"Вівторок", 
		"Середа", 
		"Четвер", 
		"Пʼятниця", 
		"Субота"
	], 
	"eraNarrow": [
		"до н.е.", 
		"н.е."
	]
})