({
	"dateFormatItem-MMMEd": "E d MMM", 
	"days-standAlone-wide": [
		"Lahadi", 
		"Litini", 
		"Talata", 
		"Laraba", 
		"Alhamis", 
		"Jumma'a", 
		"Asabar"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"Y", 
		"Y", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "HH:mm:ss v", 
	"months-standAlone-abbr": [
		"Jan", 
		"Fab", 
		"Mar", 
		"Afr", 
		"May", 
		"Yun", 
		"Yul", 
		"Aug", 
		"Sat", 
		"Okt", 
		"Nuw", 
		"Dis"
	], 
	"days-standAlone-narrow": [
		"L", 
		"L", 
		"T", 
		"L", 
		"A", 
		"J", 
		"A"
	], 
	"dateFormat-long": "d MMMM, yyyy", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "d MMM, yyyy", 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-ms": "mm:ss", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"months-standAlone-wide": [
		"Janairu", 
		"Fabrairu", 
		"Maris", 
		"Afrilu", 
		"Mayu", 
		"Yuni", 
		"Yuli", 
		"Augusta", 
		"Satumba", 
		"Oktoba", 
		"Nuwamba", 
		"Disamba"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Jan", 
		"Fab", 
		"Mar", 
		"Afr", 
		"May", 
		"Yun", 
		"Yul", 
		"Aug", 
		"Sat", 
		"Okt", 
		"Nuw", 
		"Dis"
	], 
	"timeFormat-short": "HH:mm", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"days-format-abbr": [
		"Lah", 
		"Lit", 
		"Tal", 
		"Lar", 
		"Alh", 
		"Jum", 
		"Asa"
	], 
	"pm": "PM", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"L", 
		"L", 
		"T", 
		"L", 
		"A", 
		"J", 
		"A"
	], 
	"dateFormatItem-MEd": "E, d-M", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"Y", 
		"Y", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"am": "AM", 
	"days-standAlone-abbr": [
		"Lah", 
		"Lit", 
		"Tal", 
		"Lar", 
		"Alh", 
		"Jum", 
		"Asa"
	], 
	"dateFormat-short": "d/M/yy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM yyyy", 
	"dateFormat-full": "EEEE, d MMMM, yyyy", 
	"dateFormatItem-Md": "M-d", 
	"dateFormatItem-yMEd": "EEE, d/M/yyyy", 
	"months-format-wide": [
		"Janairu", 
		"Fabrairu", 
		"Maris", 
		"Afrilu", 
		"Mayu", 
		"Yuni", 
		"Yuli", 
		"Augusta", 
		"Satumba", 
		"Oktoba", 
		"Nuwamba", 
		"Disamba"
	], 
	"dateFormatItem-d": "d", 
	"days-format-wide": [
		"Lahadi", 
		"Litini", 
		"Talata", 
		"Laraba", 
		"Alhamis", 
		"Jumma'a", 
		"Asabar"
	]
})