/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli Self Service Station",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Service Request Manager",
	About: "關於",
	Help: "說明",
	Logout: "登出",
	Welcome: "歡迎使用",
	// Login widget
	LoginHeading: "Maximo 登入",
	Username: "使用者名稱",
	Password: "密碼",
	Login: "登入",
	InvalidLogin: "「使用者名稱」或「密碼」不正確。請再試一次。",
	NotAuthorized: "此使用者無權使用應用程式",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "顯示所選橫列的明細",
	ApproveSelectedRequest: "核准選取的申請",
	RejectSelectedRequest: "拒絕選取的申請",
	ShowDetails: "顯示明細",
	Details:"明細",
	MyCatalogRequestHeading: "我的申請",
	MyApprovalHeading: "我的核准",	
	Refresh: "重新整理",
	// my catalog request grid column headings
	TotalCost: "總成本",
	ChangeDate: "變更日期",
	RequestedBy: "申請者",
	Status: "狀態",
	Quantity: "數量",
	UnitCost: "單位成本",
	Description: "說明",
	ItemNum: "要求類型",
	RequestedFor: "申請使用者",
	ItemSetID: "項目集 ID",
	DateEntered: "輸入的日期",
	MRNum: "MRNUM",
	Priority: "優先順序",
	SiteID: "場所 ID",
	MRLINEID: "MRLINE ID",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "專案",
	Name: "名稱",
	ServiceOwner: "服務擁有者",
	StatusDate: "狀態時間",
	DueDate: "到期日",
	CreatedDate: "已建立",
	StartDate: "目標開始時間",
	OfferingDescription: "申請說明",
	Approval: "核准",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "建立新的申請",
	CatalogOfferingPrompt: "服務型錄供應項目",
	CreateRequestStatus: "已順利提交申請",
	CreateRequestButtonLabel: "確定",
	CancelButtonLabel: "取消",
	
	// Navigator widget
	Home: "首頁",
	Back: "上一步", 
	Forward: "下一步",
	HomeBreadcrumb: "首頁",
	Search: "搜尋",
	SearchResults: "搜尋結果",
	Close: "關閉",
	IncidentsLabel: "說明摘記卷及支援",
	IncidentsDesc: "開啟現有資產或服務的說明摘記卷。",
	RequestsLabel: "申請新的服務",
	RequestsDesc: "開啟獲得新資產或服務的申請。",
	RecentsLabel: "常見的申請",
	RecentsDesc: "易於存取您最常申請的服務",
	None: "無",
	NA: "N/A",
	//branch in navigator tree
	Directory: "目錄",
	//leaf in navigator tree
	Panel: "畫面",
	// DateRange Widget
	DurationLabel: "在這段持續時間",
	MonthsLabel: "月",
	WeeksLabel: "週",
	DaysLabel: "日",
	ForeverLabel: "永遠",
	StartDateLabel: "開始日期",
	EndDateLabel: "結束日期",
	StartTime: "開始時間",
	EndTime: "結束時間",
	UntilLabel: "直到這個日期",
	InvalidDurationMessage: "持續時間必須大於 0",
	InvalidDateMessage: "這不是有效日期",
	DateEarlyMessage: "這是在 ${0} (最早可允許的日期) 之前",
	DateLateMessage: "這是在 ${0} (最晚可允許的日期) 之後",
	MissingDateMessage: "需要這個日期",

	Loading: "正在載入...",
	RecentActivity: "最近活動",
	NoRecentActivity: "沒有最近活動",
	ManageRequests: "管理申請",
	ManageRequestsLink: "管理申請...",
	ManageApprovalsLink: "管理核准...",
	ManageApprovals: "管理核准",

	//General
	OK : "確定",
	Cancel : "取消",
	Select: "選取",
	Total: "總數",
	TotalLabel: "總計：",
	
	// error messages
	MemChunkError: "%1 記憶體必須是 %2MB 的倍數",
	CTJZH2301I: "CTJZH2301I：抱歉，找不到相符的項目。",
	CTJZH2302I: "CTJZH2302I：已順利登入。",
	CTJZH2303I: "CTJZH2303I：您未登入。",
	CTJZH2304I: "CTJZH2304I：您必須選擇一部虛擬伺服器。",
	
	CTJZH2301W: "CTJZH2301W：無法擷取可用開始日期的清單，作為保留之用。",
	CTJZH2302W: "CTJZH2302W：選取的伺服器已有映像檔。新的映像檔將取代現有的映像檔。",
	
	CTJZH2301E: "CTJZH2301E：建立這個申請的輸入表單時發生錯誤。",
	CTJZH2302E: "CTJZH2302E：擷取這個申請的明細時發生錯誤。",
	CTJZH2303E: "CTJZH2303E：您必須登入，才能建立申請。",
	CTJZH2304E: "CTJZH2304E：建立這個申請時發生錯誤。",
	CTJZH2305E: "CTJZH2305E：您在這些欄位中輸入了無效的值。<br>您必須更正這些錯誤，然後才能繼續。",
	CTJZH2306E: "CTJZH2306E：系統已報告建立這個申請時發生錯誤。",
	CTJZH2307E: "CTJZH2307E：您登入時發生錯誤。",
	CTJZH2308E: "CTJZH2308E：抱歉，目前不支援建立這個申請。",
	CTJZH2309E: "CTJZH2309E：內部錯誤已阻止繼續執行。",
	CTJZH2310E: "CTJZH2310E：無法顯示專案的明細，我找不到專案 ID。",
	CTJZH2311E: "CTJZH2311E：內部錯誤已阻止顯示專案的明細。",
	CTJZH2312E: "CTJZH2312E：擷取專案的明細時發生錯誤。",
	CTJZH2313E: "CTJZH2313E：無法擷取您的服務申請清單。",
	CTJZH2314E: "CTJZH2314E：擷取這個專案的明細時發生錯誤。",
	CTJZH2315E: "CTJZH2315E：無法擷取您的專案清單。",
	CTJZH2316E: "CTJZH2316E：應該顯示部分訊息，但是它具有空值、未定義的或空的程式碼，或無效的類型。",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W：確認密碼不符！", 
	CTJZH2318W: "CTJZH2318W：允許最多可以選取 5 個小組！",
	CTJZH2319W: "CTJZH2319W：使用者名稱已存在！",
	CTJZH2320W: "CTJZH2320W：允許最多可以選取 15 個使用者！",
	CTJZH2321I: "CTJZH2321I：沒有要對此申請顯示的明細",
	CTJZH2322W: "CTJZH2322W：密碼無法以空白字元開始或結束", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E：無法處理您選取的申請。",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "小組",
	UserTeams: "使用者小組",
	
	//UserStatus: "Activate user account",
	LOGINID: "登入 ID",
	AccountLegend: "帳戶設定",
	PersonalInfoLegend: "個人資訊",
	RegionalSettLegend: "區域設定",
	FirstName: "名字",
	LastName: "姓氏",
	DisplayName: "顯示名稱",
	Email: "電子郵件",
	Telephone: "電話",
	Address: "地址",
	City: "城市",
	State: "狀態",
	Country: "國家/地區",
	AccountStatus: "作用中",
	EmptyString: "               ",
	UserList: "可用的使用者",
	UserID: "使用者 ID",
	Role: "角色",
	ConfirmPassword: "確認密碼",
	InvalidConfirmPassword: "確認密碼不符",
	PressToAddTeam: "按 + 以新增小組",
	// Team Management
	TeamID: "ID",
	TeamName: "名稱",
	TeamDescription: "說明",
	UserList: "可用的使用者",
	SelectedUserList: "選取的使用者",
	TeamDetails: "小組明細",
	
	//Project Details
	ProjectTitle: "專案",
	ProjectDetails: "專案明細",
	ProjectDetailsImage: "",
	ProjectName: "專案名稱",
	ProjectDescription: "專案說明",
	ProjectType: "專案類型",
	ProjectStartDate: "開始日期",
	ProjectEndDate: "結束日期",
	ProjectTeamAccess: "小組存取",
	ProjectsDropDownEmptyLabel: "選取專案",	
	
	//WCA Projects
	WCAProjectTitle: "WebSphere CloudBurst 專案",
	WCAProjectDetails: "WebSphere CloudBurst 專案明細",
	WCAProjectPattern: "型樣名稱",
	WCAServerResourcesLegend: "資源",
	WCAServerVirtualCPU: "虛擬 CPU",
	WCAServerMemory: "主要記憶體",
	WCAPatternSelection: "選取 CloudBurst 型樣",
	
	ServerGridName: "伺服器名稱",
	ServerGridOS: "作業系統",
	ServerGridStatus: "狀態",
	ServerGridMemory: "記憶體 (%)",
	ServerGridCPU: "CPU(%)",
	ServerGridDisk: "磁碟 (%)",
	ServerGridLastUpdate: "前次更新",
	ServerGridHypervisor: "Hypervisor",
	WCAServerGridPart: "部分",
	ProjectRequestedServers: "所要求的伺服器",
	ProjectActiveServers: "作用中伺服器",
	
	ViewProjectGeneralLegend: "一般",
	ViewProjectName: "名稱",
	ViewProjectDescription: "說明",
	ViewProjectServiceOwner: "服務擁有者",
	ViewProjectType: "專案類型",
	ViewProjectStartDate: "開始日期",
	ViewProjectEndDate: "結束日期",
	ViewProjectTeamAccess: "小組存取",
	ViewProjectRequestedServer: "所要求的伺服器",
	ViewProjectActiveServers: "作用中伺服器",
	
	ViewProjectServersLegend: "伺服器",
	ViewProjectServersTitle: "伺服器",
	ViewProjectMasterImage: "主要映像檔",
	ViewProjectCreateDate: "建立日期",
	ViewProjectCreatedBy: "建立者",
	ViewProjectHypervisor: "Hypervisor",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "虛擬",
	ViewProjectPhysical: "實體",
	ViewProjectMain: "主要",
	ViewProjectSwap: "交換",
	ViewProjectDisk: "磁碟",
	ViewProjectLocal: "區域",
	ViewProjectAdditionalSoftware: "其他軟體",
	ViewProjectMemory: "記憶體",
	ViewProjectServersTotal: "總計：",
	Yes: "是",
	No: "否",
	UserExist: "使用者已存在",
	MaxTeamsExceed: "超出小組的長度上限",
	PreviewCloseTitle: "關閉區段",
	PreviewOpenTitle: "開啟區段",

	/* Service Request details */
	Application: "應用程式",
	CreatedOn: "建立時間",
	Date: "日期",
	Details: "明細",
	From: "從",
	Subject: "主旨",
	Summary: "摘要",
	To: "至",
	ViewSRDetails: "申請明細",
	ViewSRTitle: "檢視服務申請",
	ViewSRGeneral: "一般",
	ViewSRGenBanner: "這個作業可讓您核准或拒絕服務申請",
	ViewSRLastUpdate: "前次更新",
	ViewSRUpdatedBy: "更新者",
	ViewSRWorkLog: "工作日誌",
	ViewSRWorkBanner: "服務申請的工作日誌。請選取表格橫列來檢視附註的明細。",
	ViewSRNoWorkl: "沒有要顯示的工作日誌",
	ViewSRCommLog: "通訊日誌",
	ViewSRCommBanner: "服務申請的通訊日誌。請選取表格橫列來檢視附註的明細。",
	ViewSRNoComml: "沒有要顯示的通訊日誌",
	
	/* Approve Request */
	AppRequestBannerTitle: "核准",
	AppRequestBannerDescription: "核准正在等待您的輸入。您如何表決？",
	RejectRequest: "我拒絕這個申請",
	ApproveRequest: "我核准這個申請",
	ApproveSummary: "摘要",
	ApproveDetails: "明細",
	
	
	copyright: "License Material - Property of IBM Corp. &copy; IBM Coporation and other(s) 2009. IBM 是 IBM Corporation 在美國及 (或) 其他國家或地區的註冊商標。",
	AboutCopyright: "Licensed Materials - Property of IBM Corp. &copy; Copyright IBM Corp. 2009. All Rights Reserved. US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contact with IBM Corp.",
	dummy_: ""
}

