// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-coptic
({
    	"patternChars":"GyMdkHmsSEDFwWahKzYeugAZvcL",
	
	'months-format-abbr@localeAlias42':{'target':"months-format-wide",'bundle':"coptic"},
	'months-format-abbr':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'months-format-narrow@localeAlias43':{'target':"months-standAlone-narrow",'bundle':"coptic"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-format-wide':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'months-standAlone-abbr@localeAlias44':{'target':"months-format-abbr",'bundle':"coptic"},
	'months-standAlone-abbr@localeAlias45':{'target':"months-format-wide",'bundle':"coptic"},
	'months-standAlone-abbr':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-standAlone-wide@localeAlias46':{'target':"months-format-wide",'bundle':"coptic"},
	'months-standAlone-wide':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'days@localeAlias47':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias48':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias49':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias50':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias51':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias52':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias53':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias54':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias55':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias56':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias57':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias58':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias59':{'target':"eraAbbr", 'bundle':"coptic"},
	'eraNames':["ERA0","ERA1"],
	'eraAbbr':["ERA0","ERA1"],
	'eraNarrow@localeAlias60':{'target':"eraAbbr", 'bundle':"coptic"},
	'eraNarrow':["ERA0","ERA1"],
	'dateFormat@localeAlias61':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, yyyy MMMM dd",
	'dateFormat-long': "yyyy MMMM d",
	'dateFormat-medium': "yyyy MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias62':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss v",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias63':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateFormatItem-Hm':"H:mm",
	'dateFormatItem-M':"L",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMEd':"E MMMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-d':"d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"yyyy",
	'dateFormatItem-yM':"yyyy-M",
	'dateFormatItem-yMEd':"EEE, yyyy-M-d",
	'dateFormatItem-yMMM':"yyyy MMM",
	'dateFormatItem-yMMMEd':"EEE, yyyy MMM d",
	'dateFormatItem-yMMMM':"yyyy MMMM",
	'dateFormatItem-yQ':"yyyy Q",
	'dateFormatItem-yQQQ':"yyyy QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        