// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-ethiopic
({
    	"patternChars":"GyMdkHmsSEDFwWahKzYeugAZvcL",
	
	'months-format-abbr@localeAlias64':{'target':"months-format-wide",'bundle':"ethiopic"},
	'months-format-abbr':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'months-format-narrow@localeAlias65':{'target':"months-standAlone-narrow",'bundle':"ethiopic"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-format-wide':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'months-standAlone-abbr@localeAlias66':{'target':"months-format-abbr",'bundle':"ethiopic"},
	'months-standAlone-abbr@localeAlias67':{'target':"months-format-wide",'bundle':"ethiopic"},
	'months-standAlone-abbr':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-standAlone-wide@localeAlias68':{'target':"months-format-wide",'bundle':"ethiopic"},
	'months-standAlone-wide':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'days@localeAlias69':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias70':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias71':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias72':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias73':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias74':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias75':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias76':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias77':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias78':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias79':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias80':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias81':{'target':"eraAbbr", 'bundle':"ethiopic"},
	'eraNames':["ERA0","ERA1"],
	'eraAbbr':["ERA0","ERA1"],
	'eraNarrow@localeAlias82':{'target':"eraAbbr", 'bundle':"ethiopic"},
	'eraNarrow':["ERA0","ERA1"],
	'dateFormat@localeAlias83':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, yyyy MMMM dd",
	'dateFormat-long': "yyyy MMMM d",
	'dateFormat-medium': "yyyy MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias84':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss v",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias85':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateFormatItem-Hm':"H:mm",
	'dateFormatItem-M':"L",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMEd':"E MMMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-d':"d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"yyyy",
	'dateFormatItem-yM':"yyyy-M",
	'dateFormatItem-yMEd':"EEE, yyyy-M-d",
	'dateFormatItem-yMMM':"yyyy MMM",
	'dateFormatItem-yMMMEd':"EEE, yyyy MMM d",
	'dateFormatItem-yMMMM':"yyyy MMMM",
	'dateFormatItem-yQ':"yyyy Q",
	'dateFormatItem-yQQQ':"yyyy QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        