// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-japanese
({
    	"patternChars":"GyMdkHmsSEDFwWahKzYeugAZvcL",
	
	'months@localeAlias192':{'target':"months", 'bundle':"gregorian"},
	'months-format-abbr@localeAlias193':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-format-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-narrow@localeAlias194':{'target':"months-standAlone-narrow",'bundle':"gregorian"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-abbr@localeAlias195':{'target':"months-format-abbr",'bundle':"gregorian"},
	'months-standAlone-abbr@localeAlias196':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-standAlone-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias197':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-standAlone-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'days@localeAlias198':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias199':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias200':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias201':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias202':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias203':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias204':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias205':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias206':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias207':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias208':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias209':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias210':{'target':"eraAbbr", 'bundle':"japanese"},
	'eraNames':["Taika","Hakuchi","Hakuhō","Shuchō","Taihō","Keiun","Wadō","Reiki","Yōrō","Jinki","Tempyō","Tempyō-kampō","Tempyō-shōhō","Tempyō-hōji","Temphō-jingo","Jingo-keiun","Hōki","Ten-ō","Enryaku","Daidō","Kōnin","Tenchō","Shōwa","Kajō","Ninju","Saiko","Tennan","Jōgan","Genkei","Ninna","Kampyō","Shōtai","Engi","Enchō","Shōhei","Tengyō","Tenryaku","Tentoku","Ōwa","Kōhō","Anna","Tenroku","Ten-en","Jōgen","Tengen","Eikan","Kanna","Ei-en","Eiso","Shōryaku","Chōtoku","Chōhō","Kankō","Chōwa","Kannin","Jian","Manju","Chōgen","Chōryaku","Chōkyū","Kantoku","Eishō","Tengi","Kōhei","Jiryaku","Enkyū","Shōho","Shōryaku","Eiho","Ōtoku","Kanji","Kaho","Eichō","Shōtoku","Kōwa","Chōji","Kashō","Tennin","Ten-ei","Eikyū","Gen-ei","Hoan","Tenji","Daiji","Tenshō","Chōshō","Hoen","Eiji","Kōji","Tenyō","Kyūan","Ninpei","Kyūju","Hogen","Heiji","Eiryaku","Ōho","Chōkan","Eiman","Nin-an","Kaō","Shōan","Angen","Jishō","Yōwa","Juei","Genryuku","Bunji","Kenkyū","Shōji","Kennin","Genkyū","Ken-ei","Shōgen","Kenryaku","Kenpō","Shōkyū","Jōō","Gennin","Karoku","Antei","Kanki","Jōei","Tempuku","Bunryaku","Katei","Ryakunin","En-ō","Ninji","Kangen","Hōji","Kenchō","Kōgen","Shōka","Shōgen","Bun-ō","Kōchō","Bun-ei","Kenji","Kōan","Shōō","Einin","Shōan","Kengen","Kagen","Tokuji","Enkei","Ōchō","Shōwa","Bunpō","Genō","Genkyō","Shōchū","Kareki","Gentoku","Genkō","Kemmu","Engen","Kōkoku","Shōhei","Kentoku","Bunchũ","Tenju","Kōryaku","Kōwa","Genchũ","Meitoku","Kakei","Kōō","Meitoku","Ōei","Shōchō","Eikyō","Kakitsu","Bun-an","Hōtoku","Kyōtoku","Kōshō","Chōroku","Kanshō","Bunshō","Ōnin","Bunmei","Chōkyō","Entoku","Meiō","Bunki","Eishō","Taiei","Kyōroku","Tenmon","Kōji","Eiroku","Genki","Tenshō","Bunroku","Keichō","Genwa","Kan-ei","Shōho","Keian","Shōō","Meiryaku","Manji","Kanbun","Enpō","Tenwa","Jōkyō","Genroku","Hōei","Shōtoku","Kyōhō","Genbun","Kanpō","Enkyō","Kan-en","Hōryaku","Meiwa","An-ei","Tenmei","Kansei","Kyōwa","Bunka","Bunsei","Tenpō","Kōka","Kaei","Ansei","Man-en","Bunkyū","Genji","Keiō","Meiji","Taishō","Shōwa","Heisei"],
	'eraAbbr':["Taika","Hakuchi","Hakuhō","Shuchō","Taihō","Keiun","Wadō","Reiki","Yōrō","Jinki","Tempyō","Tempyō-kampō","Tempyō-shōhō","Tempyō-hōji","Temphō-jingo","Jingo-keiun","Hōki","Ten-ō","Enryaku","Daidō","Kōnin","Tenchō","Shōwa","Kajō","Ninju","Saiko","Tennan","Jōgan","Genkei","Ninna","Kampyō","Shōtai","Engi","Enchō","Shōhei","Tengyō","Tenryaku","Tentoku","Ōwa","Kōhō","Anna","Tenroku","Ten-en","Jōgen","Tengen","Eikan","Kanna","Ei-en","Eiso","Shōryaku","Chōtoku","Chōhō","Kankō","Chōwa","Kannin","Jian","Manju","Chōgen","Chōryaku","Chōkyū","Kantoku","Eishō","Tengi","Kōhei","Jiryaku","Enkyū","Shōho","Shōryaku","Eiho","Ōtoku","Kanji","Kaho","Eichō","Shōtoku","Kōwa","Chōji","Kashō","Tennin","Ten-ei","Eikyū","Gen-ei","Hoan","Tenji","Daiji","Tenshō","Chōshō","Hoen","Eiji","Kōji","Tenyō","Kyūan","Ninpei","Kyūju","Hogen","Heiji","Eiryaku","Ōho","Chōkan","Eiman","Nin-an","Kaō","Shōan","Angen","Jishō","Yōwa","Juei","Genryuku","Bunji","Kenkyū","Shōji","Kennin","Genkyū","Ken-ei","Shōgen","Kenryaku","Kenpō","Shōkyū","Jōō","Gennin","Karoku","Antei","Kanki","Jōei","Tempuku","Bunryaku","Katei","Ryakunin","En-ō","Ninji","Kangen","Hōji","Kenchō","Kōgen","Shōka","Shōgen","Bun-ō","Kōchō","Bun-ei","Kenji","Kōan","Shōō","Einin","Shōan","Kengen","Kagen","Tokuji","Enkei","Ōchō","Shōwa","Bunpō","Genō","Genkyō","Shōchū","Kareki","Gentoku","Genkō","Kemmu","Engen","Kōkoku","Shōhei","Kentoku","Bunchũ","Tenju","Kōryaku","Kōwa","Genchũ","Meitoku","Kakei","Kōō","Meitoku","Ōei","Shōchō","Eikyō","Kakitsu","Bun-an","Hōtoku","Kyōtoku","Kōshō","Chōroku","Kanshō","Bunshō","Ōnin","Bunmei","Chōkyō","Entoku","Meiō","Bunki","Eishō","Taiei","Kyōroku","Tenmon","Kōji","Eiroku","Genki","Tenshō","Bunroku","Keichō","Genwa","Kan-ei","Shōho","Keian","Shōō","Meiryaku","Manji","Kanbun","Enpō","Tenwa","Jōkyō","Genroku","Hōei","Shōtoku","Kyōhō","Genbun","Kanpō","Enkyō","Kan-en","Hōryaku","Meiwa","An-ei","Tenmei","Kansei","Kyōwa","Bunka","Bunsei","Tenpō","Kōka","Kaei","Ansei","Man-en","Bunkyū","Genji","Keiō","Meiji","Taishō","Shōwa","Heisei"],
	'eraNarrow':["M","T","S","H"],
	'dateFormat-full': "EEEE, MMMM d, y G",
	'dateFormat-long': "MMMM d, y G",
	'dateFormat-medium': "MMM d, y G",
	'dateFormat-short': "M/d/yy",
	'timeFormat@localeAlias211':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss v",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTimeFormat': "{1} {0}" ,
	'dateFormatItem-Ed':"E d",
	'dateFormatItem-H':"H",
	'dateFormatItem-Hm':"HH:mm",
	'dateFormatItem-Hms':"HH:mm:ss",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"yyyy GGG",
	'dateFormatItem-yM':"GGGGG yy-MM",
	'dateFormatItem-yMMM':"GGGGG yy MMM",
	'dateFormatItem-yQ':"GGGGG yy Q",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        