/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Stazione Tivoli Self-service",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Service Request Manager",
	About: "Informazioni su",
	Help: "Guida",
	Logout: "Uscita",
	Welcome: "Benvenuti",
	// Login widget
	LoginHeading: "Accesso Maximo",
	Username: "Nome utente",
	Password: "Password",
	Login: "Connessione",
	InvalidLogin: "Nome utente o password non corretto. Riprovare.",
	NotAuthorized: "Questo utente non è autorizzato ad utilizzare l'applicazione",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "Mostra dettagli della riga selezionata",
	ApproveSelectedRequest: "Approva richiesta selezionata",
	RejectSelectedRequest: "Rifiuta la richiesta selezionata",
	ShowDetails: "Mostra dettagli",
	Details:"Dettagli",
	MyCatalogRequestHeading: "Richieste",
	MyApprovalHeading: "Approvazioni personali",	
	Refresh: "Aggiorna",
	// my catalog request grid column headings
	TotalCost: "Costo totale",
	ChangeDate: "Data di modifica",
	RequestedBy: "Richiesto da",
	Status: "Stato",
	Quantity: "Quantità",
	UnitCost: "Costo unitario",
	Description: "Descrizione articolo",
	ItemNum: "Tipo di richiesta",
	RequestedFor: "Richiesto per",
	ItemSetID: "ID serie di item",
	DateEntered: "Data di immissione",
	MRNum: "NUMRDM",
	Priority: "Priorità",
	SiteID: "ID sede",
	MRLINEID: "ID MRLINE",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "Progetti",
	Name: "Nome",
	ServiceOwner: "Proprietario del servizio",
	StatusDate: "Orario stato",
	DueDate: "Data di scadenza",
	CreatedDate: "Creato",
	StartDate: "Inizio previsto",
	OfferingDescription: "Descrizione richiesta",
	Approval: "Approvazione",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "Crea una nuova richiesta",
	CatalogOfferingPrompt: "Offerta del catalogo servizi",
	CreateRequestStatus: "Richiesta inoltrata correttamente",
	CreateRequestButtonLabel: "OK",
	CancelButtonLabel: "Annulla",
	
	// Navigator widget
	Home: "Home",
	Back: "Indietro", 
	Forward: "Successivo",
	HomeBreadcrumb: "Home",
	Search: "Ricerca",
	SearchResults: "Risultati della ricerca",
	Close: "Chiudi",
	IncidentsLabel: "Gestione ticket di assistenza e supporto",
	IncidentsDesc: "Aprire un ticket di assistenza per un asset o servizio esistente.",
	RequestsLabel: "Richiedi un nuovo servizio",
	RequestsDesc: "Aprire una richiesta per acquisire un nuovo asset o servizio.",
	RecentsLabel: "Richieste frequenti",
	RecentsDesc: "Accesso rapido ai servizi richiesti con maggiore frequenza.",
	None: "Nessuno",
	NA: "N/D",
	//branch in navigator tree
	Directory: "Directory",
	//leaf in navigator tree
	Panel: "Pannello",
	// DateRange Widget
	DurationLabel: "Per questa durata",
	MonthsLabel: "Mesi",
	WeeksLabel: "Settimane",
	DaysLabel: "Giorni",
	ForeverLabel: "Sempre",
	StartDateLabel: "Data di inizio",
	EndDateLabel: "Data di fine",
	StartTime: "Ora di inizio",
	EndTime: "Ora di fine",
	UntilLabel: "Fino a questa data",
	InvalidDurationMessage: "La durata deve essere maggiore di 0",
	InvalidDateMessage: "Questa non è una data valida.",
	DateEarlyMessage: "Questa data è prima del ${0}, la prima data ammissibile",
	DateLateMessage: "Questa data è dopo il ${0}, l'ultima data ammissibile",
	MissingDateMessage: "Questa data è obbligatoria",

	Loading: "Caricamento...",
	RecentActivity: "Attività recente",
	NoRecentActivity: "Nessuna attività recente",
	ManageRequests: "Gestisci richieste",
	ManageRequestsLink: "Gestisci richieste...",
	ManageApprovalsLink: "Gestisci approvazioni...",
	ManageApprovals: "Gestisci approvazioni",

	//General
	OK : "OK",
	Cancel : "Annulla",
	Select: "Seleziona",
	Total: "Totale",
	TotalLabel: "Totale: ",
	
	// error messages
	MemChunkError: "La memoria %1 deve essere un multiplo di %2MB",
	CTJZH2301I: "CTJZH2301I: Nessuna corrispondenza trovata.",
	CTJZH2302I: "CTJZH2302I: Accesso eseguito correttamente.",
	CTJZH2303I: "CTJZH2303I: L'utente non ha eseguito l'accesso.",
	CTJZH2304I: "CTJZH2304I: È necessario scegliere un server virtuale.",
	
	CTJZH2301W: "CTJZH2301W: Richiamo dell'elenco di date di inizio disponibili per la prenotazione non riuscito.",
	CTJZH2302W: "CTJZH2302W: Il server selezionato dispone già di un'immagine. La nuova immagine sostituirà quella esistente.",
	
	CTJZH2301E: "CTJZH2301E: Si è verificato un errore durante la creazione del modulo di input per questa richiesta.",
	CTJZH2302E: "CTJZH2302E: Si è verificato un errore durante il richiamo dei dettagli di questa richiesta.",
	CTJZH2303E: "CTJZH2303E: È necessario aver eseguito l'accesso per creare una richiesta.",
	CTJZH2304E: "CTJZH2304E: Si è verificato un errore durante la creazione di questa richiesta.",
	CTJZH2305E: "CTJZH2305E: I campi di input contengono valori non validi.<br>È necessario correggere questi errori prima di continuare.",
	CTJZH2306E: "CTJZH2306E: Il sistema ha segnalato un errore nella creazione di questa richiesta.",
	CTJZH2307E: "CTJZH2307E: Si è verificato un errore durante l'accesso.",
	CTJZH2308E: "CTJZH2308E: La creazione di questa richiesta non è attualmente supportata.",
	CTJZH2309E: "CTJZH2309E: Un errore interno impedisce di continuare.",
	CTJZH2310E: "CTJZH2310E: Visualizzazione dei dettagli del progetto non riuscita, impossibile trovare un ID progetto.",
	CTJZH2311E: "CTJZH2311E: Un errore interno impedisce di visualizzare i dettagli del progetto.",
	CTJZH2312E: "CTJZH2312E: Si è verificato un errore durante il richiamo dei dettagli del progetto.",
	CTJZH2313E: "CTJZH2313E: Richiamo dell'elenco di richieste di servizio non riuscito.",
	CTJZH2314E: "CTJZH2314E: Si è verificato un errore durante il richiamo dei dettagli di questo progetto.",
	CTJZH2315E: "CTJZH2315E: Richiamo dell'elenco di progetti non riuscito.",
	CTJZH2316E: "CTJZH2316E: Dovrebbero essere visualizzati alcuni messaggi, ma il codice è null, non definito o vuoto oppure il tipo non è valido.",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W: La password di conferma non corrisponde.", 
	CTJZH2318W: "CTJZH2318W: È consentita la selezione di un massimo di 5 team.",
	CTJZH2319W: "CTJZH2319W: Il nome utente esiste già.",
	CTJZH2320W: "CTJZH2320W: È consentita la selezione di un massimo di 15 utenti.",
	CTJZH2321I: "CTJZH2321I: Nessun dettaglio da visualizzare per questa richiesta",
	CTJZH2322W: "CTJZH2322W: La password non può iniziare o terminare con spazi", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E: L'elaborazione della richiesta selezionata non è riuscita.",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "Team",
	UserTeams: "Team dell'utente",
	
	//UserStatus: "Activate user account",
	LOGINID: "ID login",
	AccountLegend: "Impostazioni account",
	PersonalInfoLegend: "Informazioni personali",
	RegionalSettLegend: "Impostazioni internazionali",
	FirstName: "Nome",
	LastName: "Cognome",
	DisplayName: "Nome visualizzato",
	Email: "e-mail",
	Telephone: "Telefono",
	Address: "Indirizzo",
	City: "Città",
	State: "Stato",
	Country: "Paese",
	AccountStatus: "Attivo",
	EmptyString: "               ",
	UserList: "Utenti disponibili",
	UserID: "ID utente",
	Role: "Ruolo",
	ConfirmPassword: "Conferma Password",
	InvalidConfirmPassword: "La password di conferma non corrisponde",
	PressToAddTeam: "Premere + per aggiungere un team",
	// Team Management
	TeamID: "ID",
	TeamName: "Nome",
	TeamDescription: "Descrizione articolo",
	UserList: "Utenti disponibili",
	SelectedUserList: "Utenti selezionati",
	TeamDetails: "Dettagli sul team",
	
	//Project Details
	ProjectTitle: "Progetto",
	ProjectDetails: "Dettagli sul progetto",
	ProjectDetailsImage: "",
	ProjectName: "Nome progetto",
	ProjectDescription: "Descrizione progetto",
	ProjectType: "Tipo di progetto",
	ProjectStartDate: "Data di inizio",
	ProjectEndDate: "Data di fine",
	ProjectTeamAccess: "Accesso al team",
	ProjectsDropDownEmptyLabel: "Selezionare un progetto",	
	
	//WCA Projects
	WCAProjectTitle: "Progetto WebSphere CloudBurst",
	WCAProjectDetails: "Dettagli progetto WebSphere CloudBurst",
	WCAProjectPattern: "Nome modello",
	WCAServerResourcesLegend: "Risorse",
	WCAServerVirtualCPU: "CPU virtuale",
	WCAServerMemory: "Memoria principale",
	WCAPatternSelection: "Selezionare un modello CloudBurst",
	
	ServerGridName: "Nome server",
	ServerGridOS: "Sistema operativo",
	ServerGridStatus: "Stato",
	ServerGridMemory: "Memoria (%)",
	ServerGridCPU: "CPU(%)",
	ServerGridDisk: "Disco(%)",
	ServerGridLastUpdate: "Ultimo aggiornamento",
	ServerGridHypervisor: "Hypervisor",
	WCAServerGridPart: "Componente",
	ProjectRequestedServers: "Server richiesti",
	ProjectActiveServers: "Server attivi",
	
	ViewProjectGeneralLegend: "Generale",
	ViewProjectName: "Nome",
	ViewProjectDescription: "Descrizione articolo",
	ViewProjectServiceOwner: "Proprietario del servizio",
	ViewProjectType: "Tipo di progetto",
	ViewProjectStartDate: "Data di inizio",
	ViewProjectEndDate: "Data di fine",
	ViewProjectTeamAccess: "Accesso al team",
	ViewProjectRequestedServer: "Server richiesti",
	ViewProjectActiveServers: "Server attivi",
	
	ViewProjectServersLegend: "Server",
	ViewProjectServersTitle: "Server",
	ViewProjectMasterImage: "Immagine master",
	ViewProjectCreateDate: "Data creazione",
	ViewProjectCreatedBy: "Creato da",
	ViewProjectHypervisor: "Hypervisor",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "Virtuale",
	ViewProjectPhysical: "Fisico",
	ViewProjectMain: "Principale",
	ViewProjectSwap: "Swap",
	ViewProjectDisk: "Disco",
	ViewProjectLocal: "Locale",
	ViewProjectAdditionalSoftware: "Software aggiuntivo",
	ViewProjectMemory: "Memoria",
	ViewProjectServersTotal: "Totale: ",
	Yes: "Sì",
	No: "No",
	UserExist: "L'utente esiste già",
	MaxTeamsExceed: "Supera la lunghezza massima per il team",
	PreviewCloseTitle: "Chiudi sezione",
	PreviewOpenTitle: "Apri sezione",

	/* Service Request details */
	Application: "Applicazione",
	CreatedOn: "Creato il",
	Date: "Data",
	Details: "Dettagli",
	From: "Da",
	Subject: "Oggetto",
	Summary: "Riepilogo",
	To: "A",
	ViewSRDetails: "Dettagli richiesta",
	ViewSRTitle: "Visualizza richiesta di servizio",
	ViewSRGeneral: "Generale",
	ViewSRGenBanner: "Questa attività consente di approvare o rifiutare una richiesta di servizio",
	ViewSRLastUpdate: "Ultimo aggiornamento",
	ViewSRUpdatedBy: "Aggiornato da",
	ViewSRWorkLog: "Registro lavori",
	ViewSRWorkBanner: "Registro lavori per la richiesta di servizio. Selezionare la riga di tabella per visualizzare i dettagli della nota.",
	ViewSRNoWorkl: "Nessun registro lavori da visualizzare",
	ViewSRCommLog: "Registro comunicazioni",
	ViewSRCommBanner: "Registro comunicazioni per la richiesta di servizio. Selezionare la riga di tabella per visualizzare i dettagli della nota.",
	ViewSRNoComml: "Nessun registro comunicazioni da visualizzare",
	
	/* Approve Request */
	AppRequestBannerTitle: "Approvazione",
	AppRequestBannerDescription: "Un'approvazione è in attesa dell'input dell'utente. Quale è la scelta?",
	RejectRequest: "Rifiuto questa richiesta",
	ApproveRequest: "Approvo questa richiesta",
	ApproveSummary: "Riepilogo",
	ApproveDetails: "Dettagli",
	
	
	copyright: "Materiale su licenza - Proprietà di IBM Corp. &copy; IBM Coporation e altri 2009. IBM è un marchio registrato di IBM Corporation negli Stati Uniti e/o in altri paesi.",
	AboutCopyright: "Materiale su licenza - Proprietà di IBM Corp. &copy; Copyright IBM Corp. 2009. Tutti i diritti riservati. Limitazioni previste per gli utenti del Governo degli Stati Uniti - L'uso, la duplicazione o la divulgazione sono limitati dal GSA ADP Schedule Contract con IBM Corp.",
	dummy_: ""
}

