({
	"dateFormatItem-yM": "yyyy-M", 
	"field-dayperiod": "Dayperiod", 
	"field-minute": "Minuto", 
	"dateFormatItem-MMMEd": "E MMM d", 
	"dateFormatItem-yQQQ": "yyyy QQQ", 
	"field-weekday": "Araw ng Linggo", 
	"days-standAlone-wide": [
		"Linggo", 
		"Lunes", 
		"Martes", 
		"Miyerkules", 
		"Huwebes", 
		"Biyernes", 
		"Sabado"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"E", 
		"P", 
		"M", 
		"A", 
		"M", 
		"H", 
		"H", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-era": "Era", 
	"field-hour": "Oras", 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "HH:mm:ss v", 
	"months-standAlone-abbr": [
		"Ene", 
		"Peb", 
		"Mar", 
		"Abr", 
		"May", 
		"Hun", 
		"Hul", 
		"Ago", 
		"Set", 
		"Okt", 
		"Nob", 
		"Dis"
	], 
	"dateFormatItem-yMMM": "yyyy MMM", 
	"days-standAlone-narrow": [
		"L", 
		"L", 
		"M", 
		"M", 
		"H", 
		"B", 
		"S"
	], 
	"eraAbbr": [
		"BCE", 
		"CE"
	], 
	"dateFormat-long": "MMMM d, yyyy", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Zone", 
	"dateFormat-medium": "MMM d, yyyy", 
	"dateFormatItem-yyMM": "yy-MM", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-yMMMM": "yyyy MMMM", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Taon", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"months-standAlone-wide": [
		"Enero", 
		"Pebrero", 
		"Marso", 
		"Abril", 
		"Mayo", 
		"Hunyo", 
		"Hulyo", 
		"Agosto", 
		"Setyembre", 
		"Oktubre", 
		"Nobyembre", 
		"Disyembre"
	], 
	"field-week": "Linggo", 
	"dateFormatItem-MMMMEd": "E MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Ene", 
		"Peb", 
		"Mar", 
		"Abr", 
		"May", 
		"Hun", 
		"Hul", 
		"Ago", 
		"Set", 
		"Okt", 
		"Nob", 
		"Dis"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Buwan", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"Lin", 
		"Lun", 
		"Mar", 
		"Mye", 
		"Huw", 
		"Bye", 
		"Sab"
	], 
	"pm": "PM", 
	"days-format-narrow": [
		"L", 
		"L", 
		"M", 
		"M", 
		"H", 
		"B", 
		"S"
	], 
	"field-second": "Segundo", 
	"field-day": "Araw", 
	"dateFormatItem-MEd": "E, M-d", 
	"months-format-narrow": [
		"E", 
		"P", 
		"M", 
		"A", 
		"M", 
		"H", 
		"H", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"am": "AM", 
	"days-standAlone-abbr": [
		"Lin", 
		"Lun", 
		"Mar", 
		"Miy", 
		"Huw", 
		"Biy", 
		"Sab"
	], 
	"dateFormat-short": "M/d/yy", 
	"dateFormatItem-yMMMEd": "EEE, yyyy MMM d", 
	"dateFormat-full": "EEEE, MMMM dd yyyy", 
	"dateFormatItem-Md": "M-d", 
	"dateFormatItem-yMEd": "EEE, yyyy-M-d", 
	"months-format-wide": [
		"Enero", 
		"Pebrero", 
		"Marso", 
		"Abril", 
		"Mayo", 
		"Hunyo", 
		"Hulyo", 
		"Agosto", 
		"Setyembre", 
		"Oktubre", 
		"Nobyembre", 
		"Disyembre"
	], 
	"quarters-format-wide": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-wide": [
		"Linggo", 
		"Lunes", 
		"Martes", 
		"Miyerkules", 
		"Huwebes", 
		"Biyernes", 
		"Sabado"
	]
})