/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli-Self-Service-Station",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Manager der Serviceanfrage",
	About: "Produktinformation",
	Help: "Hilfe",
	Logout: "Abmelden",
	Welcome: "Willkommen",
	// Login widget
	LoginHeading: "Maximo-Anmeldung",
	Username: "Benutzername",
	Password: "Kennwort",
	Login: "Anmelden",
	InvalidLogin: "Der Benutzername oder das Kennwort ist ungültig. Wiederholen Sie die Eingabe.",
	NotAuthorized: "Dieser Benutzer ist nicht berechtigt, die Anwendung zu verwenden.",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "Details der ausgewählten Zeile anzeigen",
	ApproveSelectedRequest: "Ausgewählte Anfrage genehmigen",
	RejectSelectedRequest: "Ausgewählte Anfrage ablehnen",
	ShowDetails: "Details anzeigen",
	Details:"Details",
	MyCatalogRequestHeading: "Eigene Anfragen",
	MyApprovalHeading: "Eigene Genehmigungen",	
	Refresh: "Aktualisieren",
	// my catalog request grid column headings
	TotalCost: "Gesamtkosten",
	ChangeDate: "Änderungsdatum",
	RequestedBy: "Angefordert von",
	Status: "Status",
	Quantity: "Menge",
	UnitCost: "Kosten/Einheit",
	Description: "Beschreibung",
	ItemNum: "Anforderungstyp",
	RequestedFor: "Angefordert für",
	ItemSetID: "Artikelsatz-ID",
	DateEntered: "Eingabedatum",
	MRNum: "MANUM",
	Priority: "Priorität",
	SiteID: "Standort-ID",
	MRLINEID: "MAPOS-ID",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "Projekte",
	Name: "Name",
	ServiceOwner: "Serviceeigentümer",
	StatusDate: "Statuszeit",
	DueDate: "Fälligkeitsdatum",
	CreatedDate: "Erstellt",
	StartDate: "Soll-Start",
	OfferingDescription: "Anfragebeschreibung",
	Approval: "Genehmigung",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "Neue Anfrage erstellen",
	CatalogOfferingPrompt: "Service-Catalog-Angebot",
	CreateRequestStatus: "Anfrage erfolgreich übergeben",
	CreateRequestButtonLabel: "OK",
	CancelButtonLabel: "Abbrechen",
	
	// Navigator widget
	Home: "Home",
	Back: "Zurück", 
	Forward: "Weiter",
	HomeBreadcrumb: "Home",
	Search: "Suchfelder",
	SearchResults: "Suchergebnisse",
	Close: "Schließen",
	IncidentsLabel: "Hilfeticket und Unterstützung",
	IncidentsDesc: "Hilfeticket für eine vorhandene Anlage oder einen vorhandenen Server öffnen.",
	RequestsLabel: "Neuen Service anfordern",
	RequestsDesc: "Anfrage zur Anforderung einer neuen Anlage oder eines neuen Service.",
	RecentsLabel: "Häufig übergebene Anfragen",
	RecentsDesc: "Problemloser Zugriff auf die am häufigsten angefragten Services.",
	None: "Ohne",
	NA: "Nicht zutreffend",
	//branch in navigator tree
	Directory: "Verzeichnis",
	//leaf in navigator tree
	Panel: "Anzeige",
	// DateRange Widget
	DurationLabel: "Für diese Dauer",
	MonthsLabel: "Monate",
	WeeksLabel: "Wochen",
	DaysLabel: "Tage",
	ForeverLabel: "Für immer",
	StartDateLabel: "Startdatum",
	EndDateLabel: "Enddatum",
	StartTime: "Startzeit",
	EndTime: "Endzeit",
	UntilLabel: "Bis zu diesem Datum",
	InvalidDurationMessage: "Dauer muss größer als 0 sein",
	InvalidDateMessage: "Dies ist kein gültiges Datum",
	DateEarlyMessage: "Diese Datum liegt vor ${0}, dem frühestmöglichen Datum",
	DateLateMessage: "Dieses Datum liegt nach ${0}, dem spätestmöglichen Datum",
	MissingDateMessage: "Dieses Datum ist erforderlich",

	Loading: "Laden....",
	RecentActivity: "Letzte Aktivität",
	NoRecentActivity: "Keine letzte Aktivität",
	ManageRequests: "Anfragen verwalten",
	ManageRequestsLink: "Anfragen verwalten...",
	ManageApprovalsLink: "Genehmigungen verwalten...",
	ManageApprovals: "Genehmigungen verwalten",

	//General
	OK : "OK",
	Cancel : "Abbrechen",
	Select: "Auswählen",
	Total: "Summe",
	TotalLabel: "Summe: ",
	
	// error messages
	MemChunkError: "Der Hauptspeicher von %1 muss ein Vielfaches von %2 MB sein",
	CTJZH2301I: "CTJZH2301I: Es wurden keine Übereinstimmungen gefunden.",
	CTJZH2302I: "CTJZH2302I: Anmeldung erfolgreich.",
	CTJZH2303I: "CTJZH2303I: Sie sind nicht angemeldet.",
	CTJZH2304I: "CTJZH2303I: Sie müssen einen virtuellen Server auswählen",
	
	CTJZH2301W: "CTJZH2301W: Fehler beim Abrufen der Liste verfügbarer Startdaten für Ihre Reservierung.",
	CTJZH2302W: "CTJZH2302W: Der ausgewählte Server hat bereits ein Image. Das vorhandene Image wird durch das neue Image ersetzt.",
	
	CTJZH2301E: "CTJZH2301E: Beim Erstellen des Eingabeformulars für diese Anfrage ist ein Fehler aufgetreten.",
	CTJZH2302E: "CTJZH2302E: Beim Abrufen der Anfragedetails ist ein Fehler aufgetreten.",
	CTJZH2303E: "CTJZH2303E: Sie müssen angemeldet sein, um eine Anfrage erstellen zu können.",
	CTJZH2304E: "CTJZH2304E: Beim Erstellen dieser Anfrage ist ein Fehler aufgetreten.",
	CTJZH2305E: "CTJZH2305E: Sie haben Eingabefelder mit ungültigen Werten.<br>Diese Fehler müssen korrigiert werden, bevor Sie die Verarbeitung fortsetzen können.",
	CTJZH2306E: "CTJZH2306E: Das System hat beim Erstellen dieser Anfrage einen Fehler gemeldet.",
	CTJZH2307E: "CTJZH2307E: Beim Anmelden ist ein Fehler aufgetreten.",
	CTJZH2308E: "CTJZH2308E: Diese Anfrage wird derzeit nicht unterstützt.",
	CTJZH2309E: "CTJZH2309E: Es ist ein interner Fehler aufgetreten, der die weitere Verarbeitung verhindert.",
	CTJZH2310E: "CTJZH2310E: Fehler beim Anzeigen der Projektdetails. Die Projekt-ID wurde nicht gefunden.",
	CTJZH2311E: "CTJZH2311E: Es ist ein interner Fehler aufgetreten, der die Anzeige der Projektdetails verhindert.",
	CTJZH2312E: "CTJZH2312E: Beim Abrufen der Projektdetails ist ein Fehler aufgetreten.",
	CTJZH2313E: "CTJZH2313E: Fehler beim Abrufen der Liste der Serviceanfragen.",
	CTJZH2314E: "CTJZH2314E: Beim Abrufen der Projektdetails ist ein Fehler aufgetreten.",
	CTJZH2315E: "CTJZH2315E: Fehler beim Abrufen der Projektliste.",
	CTJZH2316E: "CTJZH2316E: Es sollte eine Nachricht angezeigt werden, aber die Nachricht hat einen Nullwert, sie ist nicht definiert, mit einem leeren Code definiert, oder sie hat einen ungültigen Typ.",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W: Kennwort und zur Bestätigung erneut eingegebenes Kennwort stimmen nicht überein!", 
	CTJZH2318W: "CTJZH2318W: Es dürfen maximal 5 Teams ausgewählt werden!",
	CTJZH2319W: "CTJZH2319W: Der Benutzername ist bereits vorhanden!",
	CTJZH2320W: "CTJZH2320W: Es dürfen maximal 15 Benutzer ausgewählt werden!",
	CTJZH2321I: "CTJZH2321I: Es sind keine Details vorhanden, die für diese Anfrage angezeigt werden könnten.",
	CTJZH2322W: "CTJZH2322W: Ein Kennwort darf nicht mit einem Leerzeichen beginnen oder enden.", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E: Fehler bei der Verarbeitung der ausgewählten Anfrage.",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "Team",
	UserTeams: "Benutzerteams",
	
	//UserStatus: "Activate user account",
	LOGINID: "Anmelde-ID",
	AccountLegend: "Kontoeinstellungen",
	PersonalInfoLegend: "Persönliche Informationen",
	RegionalSettLegend: "Ländereinstellungen",
	FirstName: "Vorname",
	LastName: "Nachname",
	DisplayName: "Anzeigename",
	Email: "E-Mail",
	Telephone: "Telefon",
	Address: "Adresse",
	City: "Stadt",
	State: "Status",
	Country: "Land",
	AccountStatus: "Aktiv",
	EmptyString: "               ",
	UserList: "Verfügbare Benutzer",
	UserID: "Benutzer-ID",
	Role: "Rolle",
	ConfirmPassword: "Kennwort bestätigen",
	InvalidConfirmPassword: "Zur Bestätigung eingegebenes Kennwort ist nicht mit dem Kennwort identisch.",
	PressToAddTeam: "Drücken Sie die Taste mit dem Pluszeichen (+), um das Team hinzuzufügen.",
	// Team Management
	TeamID: "ID",
	TeamName: "Name",
	TeamDescription: "Beschreibung",
	UserList: "Verfügbare Benutzer",
	SelectedUserList: "Ausgewählte Benutzer",
	TeamDetails: "Teamdetails",
	
	//Project Details
	ProjectTitle: "Projekt",
	ProjectDetails: "Projektdetails",
	ProjectDetailsImage: "",
	ProjectName: "Projektname",
	ProjectDescription: "Projektbeschreibung",
	ProjectType: "Projekttyp",
	ProjectStartDate: "Startdatum",
	ProjectEndDate: "Enddatum",
	ProjectTeamAccess: "Teamzugriff",
	ProjectsDropDownEmptyLabel: "Projekt auswählen",	
	
	//WCA Projects
	WCAProjectTitle: "WebSphere-CloudBurst-Projekt",
	WCAProjectDetails: "Details des WebSphere-CloudBurst-Projekts",
	WCAProjectPattern: "Mustername",
	WCAServerResourcesLegend: "Ressourcen",
	WCAServerVirtualCPU: "Virtuelle CPU",
	WCAServerMemory: "Hauptspeicher",
	WCAPatternSelection: "CloudBurst-Muster auswählen",
	
	ServerGridName: "Servername",
	ServerGridOS: "Betriebssystem",
	ServerGridStatus: "Status",
	ServerGridMemory: "Hauptspeicher (%)",
	ServerGridCPU: "CPU (%)",
	ServerGridDisk: "Plattenspeicherplatz (%)",
	ServerGridLastUpdate: "Letzte Aktualisierung",
	ServerGridHypervisor: "Hypervisor",
	WCAServerGridPart: "Komponente",
	ProjectRequestedServers: "Angeforderte Server",
	ProjectActiveServers: "Aktive Server",
	
	ViewProjectGeneralLegend: "Allgemein",
	ViewProjectName: "Name",
	ViewProjectDescription: "Beschreibung",
	ViewProjectServiceOwner: "Serviceeigentümer",
	ViewProjectType: "Projekttyp",
	ViewProjectStartDate: "Startdatum",
	ViewProjectEndDate: "Enddatum",
	ViewProjectTeamAccess: "Teamzugriff",
	ViewProjectRequestedServer: "Angeforderte Server",
	ViewProjectActiveServers: "Aktive Server",
	
	ViewProjectServersLegend: "Server",
	ViewProjectServersTitle: "Server",
	ViewProjectMasterImage: "Master-Image",
	ViewProjectCreateDate: "Erstellungsdatum",
	ViewProjectCreatedBy: "Erstellt von",
	ViewProjectHypervisor: "Hypervisor",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "Virtuell",
	ViewProjectPhysical: "Physisch",
	ViewProjectMain: "Haupt",
	ViewProjectSwap: "Auslagerung",
	ViewProjectDisk: "Platte",
	ViewProjectLocal: "Lokal",
	ViewProjectAdditionalSoftware: "Zusätzliche Software",
	ViewProjectMemory: "Hauptspeicher",
	ViewProjectServersTotal: "Summe: ",
	Yes: "Ja",
	No: "Nein",
	UserExist: "Benutzer ist bereits vorhanden",
	MaxTeamsExceed: "Überschreitet die maximal zulässige Länge für das Team",
	PreviewCloseTitle: "Abschnitt schließen",
	PreviewOpenTitle: "Abschnitt öffnen",

	/* Service Request details */
	Application: "Anwendung",
	CreatedOn: "Erstellt am",
	Date: "Datum",
	Details: "Details",
	From: "Von",
	Subject: "Betreff",
	Summary: "Zusammenfassung",
	To: "Bis",
	ViewSRDetails: "Anfragedetails",
	ViewSRTitle: "Serviceanfrage anzeigen",
	ViewSRGeneral: "Allgemein",
	ViewSRGenBanner: "Mit dieser Aufgabe können Sie eine Serviceanfrage genehmigen oder ablehnen.",
	ViewSRLastUpdate: "Letzte Aktualisierung",
	ViewSRUpdatedBy: "Aktualisiert von",
	ViewSRWorkLog: "Arbeitsprotokoll",
	ViewSRWorkBanner: "Das Arbeitsprotokoll für die Serviceanfrage. Wählen Sie die Tabellenzeile aus, um die Details der Anmerkung anzuzeigen.",
	ViewSRNoWorkl: "Es ist kein Arbeitsprotokoll vorhanden, das angezeigt werden könnte.",
	ViewSRCommLog: "Kommunikationsprotokoll",
	ViewSRCommBanner: "Das Kommunikationsprotokoll für die Serviceanfrage. Wählen Sie die Tabellenzeile aus, um die Details der Anmerkung anzuzeigen.",
	ViewSRNoComml: "Es ist kein Kommunikationsprotokoll vorhanden, das angezeigt werden könnte.",
	
	/* Approve Request */
	AppRequestBannerTitle: "Genehmigung",
	AppRequestBannerDescription: "Eine Genehmigung wartet auf Ihre Eingabe. Wie haben Sie entschieden?",
	RejectRequest: "Ich lehne die Anfrage ab",
	ApproveRequest: "Ich genehmige die Anfrage",
	ApproveSummary: "Zusammenfassung",
	ApproveDetails: "Details",
	
	
	copyright: "Lizenziertes Material - Eigentum der IBM Corp. &copy; IBM Coporation und andere. 2009. IBM ist eine eingetragene Marke der IBM Corporation in den USA und/oder anderen Ländern.",
	AboutCopyright: "Lizenziertes Material - Eigentum der IBM Corp. &copy; Copyright IBM Corp. 2009. Alle Rechte vorbehalten. US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contact with IBM Corp.",
	dummy_: ""
}

