/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli Self Service Station",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Service Request Manager",
	About: "Sobre",
	Help: "Ajuda",
	Logout: "Efetuar logout",
	Welcome: "Bem-vindo",
	// Login widget
	LoginHeading: "Login do Maximo",
	Username: "Nome do Usuário",
	Password: "Senha",
	Login: "de Login",
	InvalidLogin: "O Nome de Usuário ou a Senha está incorreta. Tente novamente.",
	NotAuthorized: "Este usuário não está autorizado a utilizar o aplicativo",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "Mostrar detalhes da linha selecionada",
	ApproveSelectedRequest: "Aprovar pedido selecionado",
	RejectSelectedRequest: "Rejeitar pedido selecionado",
	ShowDetails: "Mostrar detalhes",
	Details:"Detalhes",
	MyCatalogRequestHeading: "Meus Pedidos",
	MyApprovalHeading: "Minhas Aprovações",	
	Refresh: "Atualizar",
	// my catalog request grid column headings
	TotalCost: "Custo Total",
	ChangeDate: "Alterado Em",
	RequestedBy: "Solicitado Por",
	Status: "Status",
	Quantity: "Quantidade",
	UnitCost: "Unit Cost",
	Description: "Descrição",
	ItemNum: "Tipo de Pedido",
	RequestedFor: "Solicitado Para",
	ItemSetID: "ID de Conjuntos de Item",
	DateEntered: "Inserido em",
	MRNum: "MRNUM",
	Priority: "Prioridade",
	SiteID: "ID de Site",
	MRLINEID: "MRLINE ID",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "Projetos",
	Name: "Nome",
	ServiceOwner: "Proprietário do Serviço",
	StatusDate: "Horário do Status",
	DueDate: "Data de Vencimento",
	CreatedDate: "Criado",
	StartDate: "Início Previsto",
	OfferingDescription: "Descrição da Solicitação",
	Approval: "Aprovação",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "Criar um Novo Pedido",
	CatalogOfferingPrompt: "Oferta do Catálogo de Serviço",
	CreateRequestStatus: "Pedido Submetido com Êxito",
	CreateRequestButtonLabel: "OK",
	CancelButtonLabel: "Cancelar",
	
	// Navigator widget
	Home: "Home",
	Back: "Voltar", 
	Forward: "Encaminhar",
	HomeBreadcrumb: "Home",
	Search: "Buscar",
	SearchResults: "Resultados da Procura",
	Close: "Fechar",
	IncidentsLabel: "Bilhete de Ajuda e Suporte",
	IncidentsDesc: "Abra um bilhete de ajuda para um ativo ou serviço existente.",
	RequestsLabel: "Solicitar um Novo Serviço",
	RequestsDesc: "Abra um pedido para adquirir um ativo ou serviço novo.",
	RecentsLabel: "Pedidos frequentes",
	RecentsDesc: "Acesso fácil aos serviços que você solicita com mais frequência.",
	None: "Nenhum(a)",
	NA: "N/A",
	//branch in navigator tree
	Directory: "Diretório",
	//leaf in navigator tree
	Panel: "Painel",
	// DateRange Widget
	DurationLabel: "Para esta duração",
	MonthsLabel: "Meses",
	WeeksLabel: "Semanas",
	DaysLabel: "Dias",
	ForeverLabel: "Indefinidamente",
	StartDateLabel: "Data de Início",
	EndDateLabel: "Data de Término",
	StartTime: "Hora de Início",
	EndTime: "Hora de Término",
	UntilLabel: "Até esta data",
	InvalidDurationMessage: "A duração deve ser maior que 0",
	InvalidDateMessage: "Esta não é uma data válida",
	DateEarlyMessage: "Esta é anterior a ${0}, a data mais antiga permitida",
	DateLateMessage: "Esta é posterior a ${0}, a data mais recente permitida",
	MissingDateMessage: "Esta data é obrigatória",

	Loading: "Carregando...",
	RecentActivity: "Atividade Recente",
	NoRecentActivity: "Nenhuma atividade recente",
	ManageRequests: "Gerenciar Pedidos",
	ManageRequestsLink: "Gerenciar Pedidos...",
	ManageApprovalsLink: "Gerenciar Aprovações...",
	ManageApprovals: "Gerenciar Aprovações",

	//General
	OK : "OK",
	Cancel : "Cancelar",
	Select: "Selecionar",
	Total: "Total",
	TotalLabel: "Total: ",
	
	// error messages
	MemChunkError: "A memória do %1 deve ser um múltiplo de %2MB",
	CTJZH2301I: "CTJZH2301I: Nenhuma correspondência encontrada.",
	CTJZH2302I: "CTJZH2302I: Login efetuado com êxito.",
	CTJZH2303I: "CTJZH2303I: Você não efetuou login.",
	CTJZH2304I: "CTJZH2304I: É necessário escolher um servidor virtual",
	
	CTJZH2301W: "CTJZH2301W: Falha ao recuperar a lista de datas de início disponíveis para sua reserva.",
	CTJZH2302W: "CTJZH2302W: O servidor selecionado já possui uma imagem. A nova imagem substituirá a existente.",
	
	CTJZH2301E: "CTJZH2301E: Ocorreu um erro ao criar o formulário de entrada para esse pedido.",
	CTJZH2302E: "CTJZH2302E: Ocorreu um erro ao recuperar os detalhes deste pedido.",
	CTJZH2303E: "CTJZH2303E: É necessário efetuar login para criar um pedido.",
	CTJZH2304E: "CTJZH2304E: Ocorreu um erro ao criar este pedido.",
	CTJZH2305E: "CTJZH2305E: Você possui campos de entrada com valores inválidos.<br>Corrija esses erros antes de continuar.",
	CTJZH2306E: "CTJZH2306E: O sistema relatou um erro na criação deste pedido.",
	CTJZH2307E: "CTJZH2307E: Ocorreu um erro ao efetuar login.",
	CTJZH2308E: "CTJZH2308E: A criação deste pedido não é suportado atualmente.",
	CTJZH2309E: "CTJZH2309E: Um erro interno me impediu de continuar.",
	CTJZH2310E: "CTJZH2310E: Falha na exibição dos detalhes do projeto. Não consigo localizar um ID do projeto.",
	CTJZH2311E: "CTJZH2311E: Um erro interno me impediu de exibir os detalhes do projeto.",
	CTJZH2312E: "CTJZH2312E: Ocorreu um erro ao recuperar os detalhes do projeto.",
	CTJZH2313E: "CTJZH2313E: Falha ao recuperar sua lista de pedidos de serviço.",
	CTJZH2314E: "CTJZH2314E: Ocorreu um erro ao recuperar os detalhes deste projeto.",
	CTJZH2315E: "CTJZH2315E: Falha ao recuperar sua lista de projetos.",
	CTJZH2316E: "CTJZH2316E: Uma mensagem deveria ser exibida, mas o código é nulo, indefinido, vazio ou de tipo inválido.",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W: A confirmação da senha não corresponde!", 
	CTJZH2318W: "CTJZH2318W: É permitida a seleção de no máximo cinco equipes!",
	CTJZH2319W: "CTJZH2319W: O nome de usuário já existe!",
	CTJZH2320W: "CTJZH2320W: É permitida a seleção de no máximo quinze usuários!",
	CTJZH2321I: "CTJZH2321I: Nenhum detalhe a ser exibido para este pedido",
	CTJZH2322W: "CTJZH2322W: A senha não pode iniciar nem terminar com caracteres em branco", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E: Falha ao processar seu pedido selecionado.",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "Equipe",
	UserTeams: "Equipes de Usuários",
	
	//UserStatus: "Activate user account",
	LOGINID: "Login ID",
	AccountLegend: "Configurações de Conta",
	PersonalInfoLegend: "Informações Pessoais",
	RegionalSettLegend: "Configurações Regionais",
	FirstName: "Primeiro Nome",
	LastName: "Sobrenome",
	DisplayName: "Exibir Nome",
	Email: "e-Mail",
	Telephone: "Telefone",
	Address: "Endereço",
	City: "Cidade",
	State: "Estado",
	Country: "País",
	AccountStatus: "Ativo",
	EmptyString: "               ",
	UserList: "Usuários Disponíveis",
	UserID: "ID do usuário",
	Role: "Função",
	ConfirmPassword: "Confirmar Senha",
	InvalidConfirmPassword: "A senha confirmada não corresponde",
	PressToAddTeam: "Pressione + para incluir Equipe",
	// Team Management
	TeamID: "ID",
	TeamName: "Nome",
	TeamDescription: "Descrição",
	UserList: "Usuários Disponíveis",
	SelectedUserList: "Usuários Selecionados",
	TeamDetails: "Detalhes da Equipe",
	
	//Project Details
	ProjectTitle: "Projeto",
	ProjectDetails: "Detalhes do Projeto",
	ProjectDetailsImage: "",
	ProjectName: "Nome do Projeto",
	ProjectDescription: "Descrição do Projeto",
	ProjectType: "Tipo de Projeto",
	ProjectStartDate: "Data de Início",
	ProjectEndDate: "Data de Término",
	ProjectTeamAccess: "Acesso da Equipe",
	ProjectsDropDownEmptyLabel: "Selecionar um projeto",	
	
	//WCA Projects
	WCAProjectTitle: "Projeto do WebSphere CloudBurst",
	WCAProjectDetails: "Detalhes de Projeto do WebSphere CloudBurst",
	WCAProjectPattern: "Nome do Padrão",
	WCAServerResourcesLegend: "Recursos",
	WCAServerVirtualCPU: "CPU Virtual",
	WCAServerMemory: "Memória Principal",
	WCAPatternSelection: "Selecione um Padrão do CloudBurst",
	
	ServerGridName: "Nome do Servidor",
	ServerGridOS: "Sistema Operacional",
	ServerGridStatus: "Status",
	ServerGridMemory: "Memória (%)",
	ServerGridCPU: "CPU(%)",
	ServerGridDisk: "Disco(%)",
	ServerGridLastUpdate: "Última Atualização",
	ServerGridHypervisor: "Hypervisor",
	WCAServerGridPart: "Peça",
	ProjectRequestedServers: "Servidor(es) Solicitado(s)",
	ProjectActiveServers: "Servidor(es) Ativo(s)",
	
	ViewProjectGeneralLegend: "Geral",
	ViewProjectName: "Nome",
	ViewProjectDescription: "Descrição",
	ViewProjectServiceOwner: "Proprietário do Serviço",
	ViewProjectType: "Tipo de Projeto",
	ViewProjectStartDate: "Data de Início",
	ViewProjectEndDate: "Data de Término",
	ViewProjectTeamAccess: "Acesso da Equipe",
	ViewProjectRequestedServer: "Servidores Solicitados",
	ViewProjectActiveServers: "Servidores Ativos",
	
	ViewProjectServersLegend: "Servidores",
	ViewProjectServersTitle: "Servidor",
	ViewProjectMasterImage: "Imagem Master",
	ViewProjectCreateDate: "Criado Em",
	ViewProjectCreatedBy: "Criado Por",
	ViewProjectHypervisor: "Hypervisor",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "Virtual",
	ViewProjectPhysical: "Físico",
	ViewProjectMain: "Principal",
	ViewProjectSwap: "Swap",
	ViewProjectDisk: "Disco",
	ViewProjectLocal: "Local",
	ViewProjectAdditionalSoftware: "Software Adicional",
	ViewProjectMemory: "Memória",
	ViewProjectServersTotal: "Total: ",
	Yes: "Sim",
	No: "Não",
	UserExist: "O usuário já existe",
	MaxTeamsExceed: "Excede o comprimento máximo para equipe",
	PreviewCloseTitle: "Fechar Seção",
	PreviewOpenTitle: "Abrir Seção",

	/* Service Request details */
	Application: "Aplicativo",
	CreatedOn: "Criado em",
	Date: "Data",
	Details: "Detalhes",
	From: "De",
	Subject: "Assunto",
	Summary: "Resumo",
	To: "Para",
	ViewSRDetails: "Detalhes do Pedido",
	ViewSRTitle: "Visualizar Solicitação de Serviço",
	ViewSRGeneral: "Geral",
	ViewSRGenBanner: "Esta tarefa permite aprovar ou rejeitar um pedido de serviço",
	ViewSRLastUpdate: "Última atualização",
	ViewSRUpdatedBy: "Atualizado por",
	ViewSRWorkLog: "Log de Serviço",
	ViewSRWorkBanner: "Log de serviço para o pedido de serviço. Selecione a linha da tabela para exibir os detalhes da observação.",
	ViewSRNoWorkl: "Nenhum log de serviço a ser exibido",
	ViewSRCommLog: "Log de Comunicação",
	ViewSRCommBanner: "Log de comunicação para solicitação de serviço. Selecione a linha da tabela para exibir os detalhes da observação.",
	ViewSRNoComml: "Nenhum log de comunicação a ser exibido",
	
	/* Approve Request */
	AppRequestBannerTitle: "Aprovação",
	AppRequestBannerDescription: "Uma aprovação aguarda a sua entrada. Qual sua escolha?",
	RejectRequest: "Eu jeito este pedido",
	ApproveRequest: "Eu aprovo este pedido",
	ApproveSummary: "Resumo",
	ApproveDetails: "Detalhes",
	
	
	copyright: "Material de Licença - Propriedade da IBM Corp. &copy; IBM Corporation e outro(s) 2009. IBM é uma marca registrada da IBM Corporation nos Estados Unidos e/ou em outros países.",
	AboutCopyright: "Materiais Licenciados - Propriedade da IBM Corp. &copy; Copyright IBM Corp. 2009. Todos os Direitos Reservados. Direitos Restritos para Usuários do Governo dos Estados Unidos - Uso, duplicação ou divulgação restritos pelo documento GSA ADP Schedule Contract com a IBM Corp.",
	dummy_: ""
}

