({
	"dateFormatItem-yM": "M-yyyy", 
	"dateFormatItem-yQ": "Q yyyy", 
	"field-minute": "Minuto", 
	"eraNames": [
		"antes de Cristo", 
		"despois de Cristo"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ yyyy", 
	"field-weekday": "Día da semana", 
	"days-standAlone-wide": [
		"Domingo", 
		"Luns", 
		"Martes", 
		"Mércores", 
		"Xoves", 
		"Venres", 
		"Sábado"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"X", 
		"F", 
		"M", 
		"A", 
		"M", 
		"X", 
		"X", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-era": "Era", 
	"field-hour": "Hora", 
	"quarters-standAlone-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "HH:mm:ss v", 
	"months-standAlone-abbr": [
		"Xan", 
		"Feb", 
		"Mar", 
		"Abr", 
		"Mai", 
		"Xuñ", 
		"Xul", 
		"Ago", 
		"Set", 
		"Out", 
		"Nov", 
		"Dec"
	], 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"days-standAlone-narrow": [
		"D", 
		"L", 
		"M", 
		"M", 
		"X", 
		"V", 
		"S"
	], 
	"eraAbbr": [
		"a.C.", 
		"d.C."
	], 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "dd MMMM yyyy", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Fuso horario", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM, yyyy", 
	"dateFormatItem-yyMM": "MM/yy", 
	"quarters-standAlone-wide": [
		"1o trimestre", 
		"2o trimestre", 
		"3o trimestre", 
		"4o trimestre"
	], 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-yMMMM": "MMMM yyyy", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Ano", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"field-week": "Semana", 
	"months-standAlone-wide": [
		"Xaneiro", 
		"Febreiro", 
		"Marzo", 
		"Abril", 
		"Maio", 
		"Xuño", 
		"Xullo", 
		"Agosto", 
		"Setembro", 
		"Outubro", 
		"Novembro", 
		"Decembro"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Xan", 
		"Feb", 
		"Mar", 
		"Abr", 
		"Mai", 
		"Xuñ", 
		"Xul", 
		"Ago", 
		"Set", 
		"Out", 
		"Nov", 
		"Dec"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Mes", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"days-format-abbr": [
		"Dom", 
		"Lun", 
		"Mar", 
		"Mér", 
		"Xov", 
		"Ven", 
		"Sáb"
	], 
	"dateFormatItem-MMMMdd": "dd MMMM", 
	"pm": "PM", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"D", 
		"L", 
		"M", 
		"M", 
		"X", 
		"V", 
		"S"
	], 
	"field-second": "Segundo", 
	"field-day": "Día", 
	"dateFormatItem-MEd": "E, d-M", 
	"months-format-narrow": [
		"X", 
		"F", 
		"M", 
		"A", 
		"M", 
		"X", 
		"X", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"am": "AM", 
	"days-standAlone-abbr": [
		"Dom", 
		"Lun", 
		"Mar", 
		"Mér", 
		"Xov", 
		"Ven", 
		"Sáb"
	], 
	"dateFormat-short": "dd/MM/yy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM yyyy", 
	"dateFormat-full": "EEEE dd MMMM yyyy", 
	"dateFormatItem-Md": "d-M", 
	"dateFormatItem-yMEd": "EEE, d-M-yyyy", 
	"months-format-wide": [
		"Xaneiro", 
		"Febreiro", 
		"Marzo", 
		"Abril", 
		"Maio", 
		"Xuño", 
		"Xullo", 
		"Agosto", 
		"Setembro", 
		"Outubro", 
		"Novembro", 
		"Decembro"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1o trimestre", 
		"2o trimestre", 
		"3o trimestre", 
		"4o trimestre"
	], 
	"days-format-wide": [
		"Domingo", 
		"Luns", 
		"Martes", 
		"Mércores", 
		"Xoves", 
		"Venres", 
		"Sábado"
	], 
	"eraNarrow": [
		"a.C.", 
		"d.C."
	]
})