({
	"dateFormatItem-yM": "yyyy-M", 
	"field-dayperiod": "രാവിലെ/വൈകുന്നേരം", 
	"dateFormatItem-yQ": "yyyy Q", 
	"field-minute": "മിനിട്ട്", 
	"eraNames": [
		"ക്രിസ്തുവിനു് മുമ്പ്", 
		"ക്രിസ്തുവിനു് പിമ്പ്"
	], 
	"dateFormatItem-MMMEd": "MMM d, E", 
	"dateFormatItem-MMdd": "dd-MM", 
	"dateFormatItem-yQQQ": "yyyy QQQ", 
	"field-weekday": "ആഴ്ചയിലെ ദിവസം", 
	"days-standAlone-wide": [
		"ഞായര്", 
		"തിങ്കളാഴ്ച", 
		"ചൊവ്വ", 
		"ബുധന്", 
		"വ്യാഴം", 
		"വെള്ളി", 
		"ശനി"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"ജ", 
		"ഫെ", 
		"മ", 
		"ഏ", 
		"മേ", 
		"ജൂ", 
		"ജൂ", 
		"ആ", 
		"സെ", 
		"ഒ", 
		"ന", 
		"ഡി"
	], 
	"field-era": "അബ്ദം", 
	"field-hour": "മണിക്കൂര്", 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "h:mm:ss a v", 
	"months-standAlone-abbr": [
		"ജനു", 
		"ഫെബ്രു", 
		"മാര്", 
		"ഏപ്രി", 
		"മേയ്", 
		"ജൂണ്", 
		"ജൂലൈ", 
		"ആഗ", 
		"സെപ്റ്റം", 
		"ഒക്ടോ", 
		"നവം", 
		"ഡിസം"
	], 
	"dateFormatItem-yMMM": "yyyy MMM", 
	"days-standAlone-narrow": [
		"ഞ", 
		"ത", 
		"ച", 
		"ബ", 
		"വ", 
		"വ", 
		"ശ"
	], 
	"eraAbbr": [
		"ക്രി.മു.", 
		"ക്രി.പി."
	], 
	"dateFormatItem-yyyyMM": "MM-yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "yyyy, MMMM d", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "മേഖല", 
	"dateFormatItem-Hm": "h:mm a", 
	"dateFormat-medium": "yyyy, MMM d", 
	"quarters-standAlone-wide": [
		"ഒന്നാം പാദം", 
		"രണ്ടാം പാദം", 
		"മൂന്നാം പാദം", 
		"നാലാം പാദം"
	], 
	"dateTimeFormat": "{1} {0}", 
	"dateFormatItem-yMMMM": "yyyy MMMM", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "വര്ഷം", 
	"quarters-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4"
	], 
	"field-week": "ആഴ്ച", 
	"months-standAlone-wide": [
		"ജനുവരി", 
		"ഫെബ്രുവരി", 
		"മാര്ച്ച്", 
		"ഏപ്രില്", 
		"മേയ്", 
		"ജൂണ്", 
		"ജൂലൈ", 
		"ഓഗസ്റ്റ്", 
		"സെപ്റ്റംബര്", 
		"ഒക്ടോബര്", 
		"നവംബര്", 
		"ഡിസംബര്"
	], 
	"dateFormatItem-MMMMEd": "MMMM d, E", 
	"dateFormatItem-MMMd": "MMM d", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"ജനു", 
		"ഫെബ്രു", 
		"മാര്", 
		"ഏപ്രി", 
		"മേയ്", 
		"ജൂണ്", 
		"ജൂലൈ", 
		"ആഗ", 
		"സെപ്റ്റം", 
		"ഒക്ടോ", 
		"നവം", 
		"ഡിസം"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "മാസം", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"ഞാ", 
		"തി", 
		"ചൊ", 
		"ബു", 
		"വ്യാ", 
		"വെ", 
		"ശ"
	], 
	"pm": "വൈകുന്നേരം", 
	"days-format-narrow": [
		"ഞ", 
		"ത", 
		"ചൊ", 
		"ബ", 
		"വ", 
		"വ", 
		"ശ"
	], 
	"dateFormatItem-M": "L", 
	"field-second": "സെക്കന്റ്", 
	"field-day": "ദിവസം", 
	"dateFormatItem-MEd": "M/d, E", 
	"months-format-narrow": [
		"ജ", 
		"ഫെ", 
		"മ", 
		"ഏ", 
		"മേ", 
		"ജൂ", 
		"ജൂ", 
		"ആ", 
		"സെ", 
		"ഒ", 
		"ന", 
		"ഡി"
	], 
	"am": "രാവിലെ", 
	"days-standAlone-abbr": [
		"ഞാ", 
		"തി", 
		"ചൊ", 
		"ബു", 
		"വ്യാ", 
		"വെ", 
		"ശ"
	], 
	"dateFormat-short": "dd-MM-yy", 
	"dateFormatItem-yMMMEd": "yyyy MMM d, EEE", 
	"dateFormat-full": "yyyy, MMMM d, EEEE", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "yyyy-M-d, EEE", 
	"months-format-wide": [
		"ജനുവരി", 
		"ഫെബ്രുവരി", 
		"മാര്ച്ച്", 
		"ഏപ്രില്", 
		"മേയ്", 
		"ജൂണ്", 
		"ജൂലൈ", 
		"ഓഗസ്റ്റ്", 
		"സെപ്റ്റംബര്", 
		"ഒക്ടോബര്", 
		"നവംബര്", 
		"ഡിസംബര്"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"ഒന്നാം പാദം", 
		"രണ്ടാം പാദം", 
		"മൂന്നാം പാദം", 
		"നാലാം പാദം"
	], 
	"days-format-wide": [
		"ഞായര്", 
		"തിങ്കള്", 
		"ചൊവ്വ", 
		"ബുധന്", 
		"വ്യാഴം", 
		"വെള്ളി", 
		"ശനി"
	], 
	"eraNarrow": [
		"ക്രി.മു.", 
		"ക്രി.പി."
	]
})