({
	"dateFormatItem-yQ": "Q yyyy", 
	"dateFormatItem-MMMEd": "E d MMM", 
	"eraNames": [
		"tr. CN", 
		"sau CN"
	], 
	"dateFormatItem-MMdd": "dd-MM", 
	"dateFormatItem-yQQQ": "QQQ yyyy", 
	"days-standAlone-wide": [
		"Chủ nhật", 
		"Thứ hai", 
		"Thứ ba", 
		"Thứ tư", 
		"Thứ năm", 
		"Thứ sáu", 
		"Thứ bảy"
	], 
	"months-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7", 
		"8", 
		"9", 
		"10", 
		"11", 
		"12"
	], 
	"timeFormat-full": "HH:mm:ss v", 
	"dateFormatItem-yyyy": "yyyy", 
	"months-standAlone-abbr": [
		"thg 1", 
		"thg 2", 
		"thg 3", 
		"thg 4", 
		"thg 5", 
		"thg 6", 
		"thg 7", 
		"thg 8", 
		"thg 9", 
		"thg 10", 
		"thg 11", 
		"thg 12"
	], 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"days-standAlone-narrow": [
		"1", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6", 
		"7"
	], 
	"eraAbbr": [
		"tr. CN", 
		"sau CN"
	], 
	"dateFormatItem-yyyyMM": "MM-yyyy", 
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' yyyy", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormat-medium": "dd-MM-yyyy", 
	"dateTimeFormat": "{0} {1}", 
	"dateFormatItem-yMMMM": "MMMM yyyy", 
	"dateFormatItem-HHmmss": "HH:mm:ss", 
	"months-standAlone-wide": [
		"tháng một", 
		"tháng hai", 
		"tháng ba", 
		"tháng tư", 
		"tháng năm", 
		"tháng sáu", 
		"tháng bảy", 
		"tháng tám", 
		"tháng chín", 
		"tháng mười", 
		"tháng mười một", 
		"tháng mười hai"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-HHmm": "HH:mm", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"thg 1", 
		"thg 2", 
		"thg 3", 
		"thg 4", 
		"thg 5", 
		"thg 6", 
		"thg 7", 
		"thg 8", 
		"thg 9", 
		"thg 10", 
		"thg 11", 
		"thg 12"
	], 
	"timeFormat-short": "HH:mm", 
	"dateFormatItem-H": "H", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"CN", 
		"Th 2", 
		"Th 3", 
		"Th 4", 
		"Th 5", 
		"Th 6", 
		"Th 7"
	], 
	"pm": "CH", 
	"dateFormatItem-mmss": "mm:ss", 
	"dateFormatItem-MEd": "E, d-M", 
	"am": "SA", 
	"days-standAlone-abbr": [
		"CN", 
		"Th 2", 
		"Th 3", 
		"Th 4", 
		"Th 5", 
		"Th 6", 
		"Th 7"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM yyyy", 
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' yyyy", 
	"dateFormatItem-Md": "d-M", 
	"dateFormatItem-yMEd": "EEE, d-M-yyyy", 
	"months-format-wide": [
		"tháng một", 
		"tháng hai", 
		"tháng ba", 
		"tháng tư", 
		"tháng năm", 
		"tháng sáu", 
		"tháng bảy", 
		"tháng tám", 
		"tháng chín", 
		"tháng mười", 
		"tháng mười một", 
		"tháng mười hai"
	], 
	"quarters-format-wide": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-wide": [
		"Chủ nhật", 
		"Thứ hai", 
		"Thứ ba", 
		"Thứ tư", 
		"Thứ năm", 
		"Thứ sáu", 
		"Thứ bảy"
	], 
	"eraNarrow": [
		"tr. CN", 
		"sau CN"
	]
})