/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli Self Service Station",
	TSAMHeading: "Gestor de automatización de servicio",
	SRMHeading: "Service Request Manager",
	About: "Acerca de",
	Help: "Ayuda",
	Logout: "Cierre de sesión",
	Welcome: "Bienvenida",
	// Login widget
	LoginHeading: "Inicio de sesión de Maximo",
	Username: "Nombre de usuario",
	Password: "Contraseña",
	Login: "Inicio de sesión",
	InvalidLogin: "El nombre de usuario o la contraseña no son correctos. Vuelva a intentarlo.",
	NotAuthorized: "Este usuario no tiene autorización para utilizar la aplicación",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "Mostrar detalles de fila seleccionada",
	ApproveSelectedRequest: "Aprobar solicitud seleccionada",
	RejectSelectedRequest: "Rechazar solicitud seleccionada",
	ShowDetails: "Mostrar detalles",
	Details:"Detalles",
	MyCatalogRequestHeading: "Mis solicitudes",
	MyApprovalHeading: "Mis aprobaciones",	
	Refresh: "Actualizar",
	// my catalog request grid column headings
	TotalCost: "Coste total",
	ChangeDate: "Fecha de modificación",
	RequestedBy: "Solicitado por",
	Status: "Estado",
	Quantity: "Cantidad",
	UnitCost: "Coste unitario",
	Description: "Descripción",
	ItemNum: "Tipo de solicitud",
	RequestedFor: "Solicitado para",
	ItemSetID: "Conjunto de partes",
	DateEntered: "Fecha introducida",
	MRNum: "SMNUM",
	Priority: "Prioridad",
	SiteID: "ID de planta",
	MRLINEID: "ID línea SM",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "Proyectos",
	Name: "Nombre",
	ServiceOwner: "Propietario del servicio",
	StatusDate: "Hora de estado",
	DueDate: "Fecha de vencimiento",
	CreatedDate: "Creado",
	StartDate: "Inicio previsto",
	OfferingDescription: "Descripción de solicitud",
	Approval: "Aprobación",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "Crear solicitud nueva",
	CatalogOfferingPrompt: "Oferta de catálogo de servicio",
	CreateRequestStatus: "Solicitud enviada correctamente",
	CreateRequestButtonLabel: "Aceptar",
	CancelButtonLabel: "Cancelar",
	
	// Navigator widget
	Home: "Inicio",
	Back: "Atrás", 
	Forward: "Adelante",
	HomeBreadcrumb: "Inicio",
	Search: "Buscar",
	SearchResults: "Resultados de búsqueda",
	Close: "Cerrar",
	IncidentsLabel: "Tickets de ayuda y soporte",
	IncidentsDesc: "Abra un ticket de ayuda de un activo o servicio existente.",
	RequestsLabel: "Solicitar un servicio nuevo",
	RequestsDesc: "Abra una solicitud para adquirir un nuevo activo o servicio.",
	RecentsLabel: "Solicitudes frecuentes",
	RecentsDesc: "Acceso fácil a los servicios solicitados con mayor frecuencia.",
	None: "Ninguno",
	NA: "N/A",
	//branch in navigator tree
	Directory: "Directorio",
	//leaf in navigator tree
	Panel: "Panel",
	// DateRange Widget
	DurationLabel: "Para esta duración",
	MonthsLabel: "Meses",
	WeeksLabel: "Semanas",
	DaysLabel: "Días",
	ForeverLabel: "Siempre",
	StartDateLabel: "Fecha de inicio",
	EndDateLabel: "Fecha de finalización",
	StartTime: "Hora de inicio",
	EndTime: "Hora de finalización",
	UntilLabel: "Hasta esta fecha",
	InvalidDurationMessage: "La duración debe ser mayor que 0",
	InvalidDateMessage: "Esta fecha no es válida",
	DateEarlyMessage: "Esta fecha es anterior a ${0}, la fecha más temprana permitida",
	DateLateMessage: "Esta fecha es después de ${0}, la fecha más posterior permitida",
	MissingDateMessage: "Esta fecha es necesaria",

	Loading: "Cargando...",
	RecentActivity: "Actividad reciente",
	NoRecentActivity: "Ninguna actividad reciente",
	ManageRequests: "Gestionar solicitudes",
	ManageRequestsLink: "Gestionar solicitudes...",
	ManageApprovalsLink: "Gestionar aprobaciones...",
	ManageApprovals: "Gestionar aprobaciones",

	//General
	OK : "Aceptar",
	Cancel : "Cancelar",
	Select: "Seleccionar",
	Total: "Total",
	TotalLabel: "Total: ",
	
	// error messages
	MemChunkError: "La memoria %1 debe ser un múltiplo de %2MB",
	CTJZH2301I: "CTJZH2301I: Desafortunadamente, no se ha encontrado ninguna coincidencia.",
	CTJZH2302I: "CTJZH2302I: Ha iniciado sesión correctamente.",
	CTJZH2303I: "CTJZH2303I: No ha iniciado sesión.",
	CTJZH2304I: "CTJZH2304I: Debe seleccionar un servidor virtual.",
	
	CTJZH2301W: "CTJZH2301W: Error al recuperar la lista de fechas de inicio disponibles para la reserva.",
	CTJZH2302W: "CTJZH2302W: El servidor seleccionado ya tiene una imagen. La nueva imagen sustituirá la existente.",
	
	CTJZH2301E: "CTJZH2301E: Se ha producido un error al crear el formulario de entrada para esta solicitud.",
	CTJZH2302E: "CTJZH2302E: Se ha producido un error al recuperar los detalles de esta solicitud.",
	CTJZH2303E: "CTJZH2303E: Debe iniciar sesión para crear una solicitud.",
	CTJZH2304E: "CTJZH2304E: Se ha producido un error al crear esta solicitud.",
	CTJZH2305E: "CTJZH2305E: Los valores de algunos campos de entrada no son válidos.<br>Debe corregir estos errores antes de proseguir.",
	CTJZH2306E: "CTJZH2306E: El sistema ha notificado un error al crear esta solicitud.",
	CTJZH2307E: "CTJZH2307E: Se ha producido un error al iniciar sesión.",
	CTJZH2308E: "CTJZH2308E: Lamentablemente no se da soporte a la creación de esta solicitud.",
	CTJZH2309E: "CTJZH2309E: Un error interno me ha impedido continuar.",
	CTJZH2310E: "CTJZH2310E: No puedo visualizar los detalles del proyecto. No encuentro el ID del proyecto.",
	CTJZH2311E: "CTJZH2311E: Un error interno me ha impedido visualizar los detalles del proyecto.",
	CTJZH2312E: "CTJZH2312E: Se ha producido un error al recuperar los detalles del proyecto.",
	CTJZH2313E: "CTJZH2313E: No se ha podido recuperar la lista de solicitudes de servicio.",
	CTJZH2314E: "CTJZH2314E: Se ha producido un error al recuperar los detalles de este proyecto.",
	CTJZH2315E: "CTJZH2315E: No se ha podido recuperar la lista de proyectos.",
	CTJZH2316E: "CTJZH2316E: Debería aparecer algún mensaje, pero aparece un código nulo, sin definir o vacío o un tipo no válido.",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W: La contraseña de Confirmar contraseña no coincide con la contraseña especificada anteriormente.", 
	CTJZH2318W: "CTJZH2318W: Sólo se pueden seleccionar 5 equipos como máximo",
	CTJZH2319W: "CTJZH2319W: El nombre de usuario ya existe",
	CTJZH2320W: "CTJZH2320W: Sólo se pueden seleccionar 15 equipos como máximo",
	CTJZH2321I: "CTJZH2321I: No hay detalles para visualizar para esta solicitud",
	CTJZH2322W: "CTJZH2322W: La contraseña no puede empezar ni acabar con caracteres en blanco", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E: No se ha procesado correctamente la solicitud seleccionada.",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "Equ.",
	UserTeams: "Equipos de usuario",
	
	//UserStatus: "Activate user account",
	LOGINID: "ID de inicio de sesión",
	AccountLegend: "Valores de cuenta",
	PersonalInfoLegend: "Información personal",
	RegionalSettLegend: "Valores regionales",
	FirstName: "Nombre",
	LastName: "Apellido",
	DisplayName: "Nom. visual.",
	Email: "Correo electrónico",
	Telephone: "Teléfono",
	Address: "Direcc.",
	City: "Pob.",
	State: "Estado",
	Country: "País",
	AccountStatus: "Activo",
	EmptyString: "               ",
	UserList: "Usuarios disponibles",
	UserID: "ID de usuario",
	Role: "Rol",
	ConfirmPassword: "Confirmar contraseña",
	InvalidConfirmPassword: "La contraseña especificada no coincide con la del campo anterior",
	PressToAddTeam: "Pulse + para añadir un equipo",
	// Team Management
	TeamID: "ID",
	TeamName: "Nombre",
	TeamDescription: "Descripción",
	UserList: "Usuarios disponibles",
	SelectedUserList: "Usuarios seleccionados",
	TeamDetails: "Detalles de equipo",
	
	//Project Details
	ProjectTitle: "Proyecto",
	ProjectDetails: "Detalles de proyecto",
	ProjectDetailsImage: "",
	ProjectName: "Nombre del proyecto",
	ProjectDescription: "Descripción del proyecto",
	ProjectType: "Tipo de proyecto",
	ProjectStartDate: "Fecha de inicio",
	ProjectEndDate: "Fecha de finalización",
	ProjectTeamAccess: "Acceso a equipo",
	ProjectsDropDownEmptyLabel: "Seleccionar un proyecto",	
	
	//WCA Projects
	WCAProjectTitle: "Proyecto de WebSphere CloudBurst",
	WCAProjectDetails: "Detalles del proyecto de WebSphere CloudBurst",
	WCAProjectPattern: "Nombre de patrón",
	WCAServerResourcesLegend: "Recursos",
	WCAServerVirtualCPU: "CPU virtual",
	WCAServerMemory: "Memoria principal",
	WCAPatternSelection: "Seleccionar un patrón CloudBurst",
	
	ServerGridName: "Nombre del servidor",
	ServerGridOS: "Sistema operativo",
	ServerGridStatus: "Estado",
	ServerGridMemory: "Memoria (%)",
	ServerGridCPU: "CPU(%)",
	ServerGridDisk: "Disco(%)",
	ServerGridLastUpdate: "Última actualización",
	ServerGridHypervisor: "Hipervisor",
	WCAServerGridPart: "Componente",
	ProjectRequestedServers: "Servidores solicitados",
	ProjectActiveServers: "Servidores activos",
	
	ViewProjectGeneralLegend: "General",
	ViewProjectName: "Nombre",
	ViewProjectDescription: "Descripción",
	ViewProjectServiceOwner: "Propietario del servicio",
	ViewProjectType: "Tipo de proyecto",
	ViewProjectStartDate: "Fecha de inicio",
	ViewProjectEndDate: "Fecha de finalización",
	ViewProjectTeamAccess: "Acceso a equipo",
	ViewProjectRequestedServer: "Servidores solicitados",
	ViewProjectActiveServers: "Servidores activos",
	
	ViewProjectServersLegend: "Servidores",
	ViewProjectServersTitle: "Servidor",
	ViewProjectMasterImage: "Imagen maestra",
	ViewProjectCreateDate: "Fecha de creación",
	ViewProjectCreatedBy: "Creado por",
	ViewProjectHypervisor: "Hipervisor",
	ViewProjectCPU: "CPU",
	ViewProjectVirtual: "Virtual",
	ViewProjectPhysical: "Físico",
	ViewProjectMain: "Principal",
	ViewProjectSwap: "Intercambio",
	ViewProjectDisk: "Disco",
	ViewProjectLocal: "Local",
	ViewProjectAdditionalSoftware: "Software adicional",
	ViewProjectMemory: "Memoria",
	ViewProjectServersTotal: "Total: ",
	Yes: "Sí",
	No: "No",
	UserExist: "El usuario ya existe",
	MaxTeamsExceed: "Excede la longitud máxima de equipo",
	PreviewCloseTitle: "Cerrar sección",
	PreviewOpenTitle: "Abrir sección",

	/* Service Request details */
	Application: "Aplicación",
	CreatedOn: "Fecha de creación",
	Date: "Fecha",
	Details: "Detalles",
	From: "Desde",
	Subject: "Asunto",
	Summary: "Resumen",
	To: "Hasta",
	ViewSRDetails: "Detalles de solicitud",
	ViewSRTitle: "Ver solicitud de servicio",
	ViewSRGeneral: "General",
	ViewSRGenBanner: "Esta tarea permite aprobar o rechazar una solicitud de servicio",
	ViewSRLastUpdate: "Última actualización",
	ViewSRUpdatedBy: "Actualizado por",
	ViewSRWorkLog: "Registro de trabajo",
	ViewSRWorkBanner: "Registro de trabajo de la solicitud de servicio. Seleccione la fila de la tabla para ver los detalles de la nota.",
	ViewSRNoWorkl: "No hay ningún registro de trabajo por visualizar",
	ViewSRCommLog: "Registro de comunicación",
	ViewSRCommBanner: "Registro de comunicación de la solicitud de servicio. Seleccione la fila de la tabla para ver los detalles de la nota.",
	ViewSRNoComml: "No hay ningún registro de comunicación por visualizar",
	
	/* Approve Request */
	AppRequestBannerTitle: "Aprobación",
	AppRequestBannerDescription: "Una aprobación está a la espera de entrada. ¿Cómo va a votar?",
	RejectRequest: "Rechazo esta solicitud",
	ApproveRequest: "Apruebo esta solicitud",
	ApproveSummary: "Resumen",
	ApproveDetails: "Detalles",
	
	
	copyright: "Material bajo licencia - Propiedad de IBM Corp. &copy; IBM Coporation and other(s) 2009. IBM es una marca registrada de IBM Corporation en los Estados Unidos y en otros países.",
	AboutCopyright: "Materiales bajo licencia - Propiedad de IBM Corp. &copy; Copyright IBM Corp. 2009. Reservados todos los derechos. Derechos restringidos para los usuarios del gobierno de EE.UU. - Uso, duplicación y divulgación restringidos por contrato programado por GSA ADP con IBM Corp.",
	dummy_: ""
}

