// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-indian
({
    	"patternChars":"GyMdkHmsSEDFwWahKzYeugAZvcL",
	
	'months-format-abbr@localeAlias125':{'target':"months-format-wide",'bundle':"indian"},
	'months-format-abbr':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'months-format-narrow@localeAlias126':{'target':"months-standAlone-narrow",'bundle':"indian"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-wide':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'months-standAlone-abbr@localeAlias127':{'target':"months-format-abbr",'bundle':"indian"},
	'months-standAlone-abbr@localeAlias128':{'target':"months-format-wide",'bundle':"indian"},
	'months-standAlone-abbr':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias129':{'target':"months-format-wide",'bundle':"indian"},
	'months-standAlone-wide':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'days@localeAlias130':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias131':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias132':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias133':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias134':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias135':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias136':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias137':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias138':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias139':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias140':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias141':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'am':"AM",
	'pm':"PM",
	'eraNames@localeAlias142':{'target':"eraAbbr", 'bundle':"indian"},
	'eraNames':["SAKA"],
	'eraAbbr':["SAKA"],
	'eraNarrow@localeAlias143':{'target':"eraAbbr", 'bundle':"indian"},
	'eraNarrow':["SAKA"],
	'dateFormat@localeAlias144':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, yyyy MMMM dd",
	'dateFormat-long': "yyyy MMMM d",
	'dateFormat-medium': "yyyy MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias145':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss v",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias146':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateFormatItem-Hm':"H:mm",
	'dateFormatItem-M':"L",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMEd':"E MMMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-d':"d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"yyyy",
	'dateFormatItem-yM':"yyyy-M",
	'dateFormatItem-yMEd':"EEE, yyyy-M-d",
	'dateFormatItem-yMMM':"yyyy MMM",
	'dateFormatItem-yMMMEd':"EEE, yyyy MMM d",
	'dateFormatItem-yMMMM':"yyyy MMMM",
	'dateFormatItem-yQ':"yyyy Q",
	'dateFormatItem-yQQQ':"yyyy QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        