/*
THIS PRODUCT CONTAINS RESTRICTED MATERIALS OF IBM
(C) COPYRIGHT International Business Machines Corp., 2009.
All Rights Reserved * Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.
*/

/*
 * Message IDs are formed as CTJZHxxxxY where xxxx is the 4-digit
 * range of the functional component and Y is one of E, W, or I.
 * For the Web UI, the range is 2300-2999.
 */
{
	// SimpleSrmApp widget
	Title: "Tivoli Self Service Station",
	TSAMHeading: "Service Automation Manager",
	SRMHeading: "Service Request Manager (SRM)",
	About: "A propos de",
	Help: "Aide",
	Logout: "Déconnexion",
	Welcome: "Bienvenue dans",
	// Login widget
	LoginHeading: "Ouverture de session Maximo",
	Username: "Nom d'utilisateur",
	Password: "Mot de passe",
	Login: "Connexion",
	InvalidLogin: "Le nom d'utilisateur ou le mot de passe sont incorrect. Refaites une tentative.",
	NotAuthorized: "Cet utilisateur  n'est pas autorisé à utiliser l'application.",
	// MyCatalogRequestsGrid widget
	ShowSelectedDetails: "Afficher les détails de la ligne sélectionnée",
	ApproveSelectedRequest: "Approuver la demande sélectionnée",
	RejectSelectedRequest: "Rejeter la demande sélectionnée",
	ShowDetails: "Afficher les détails",
	Details:"Détails",
	MyCatalogRequestHeading: "Mes demandes",
	MyApprovalHeading: "Mes approbations",	
	Refresh: "Régénérer",
	// my catalog request grid column headings
	TotalCost: "Coût total",
	ChangeDate: "Date de modification",
	RequestedBy: "Demandeur",
	Status: "état",
	Quantity: "Quantité",
	UnitCost: "Coût unitaire",
	Description: "Description",
	ItemNum: "Type de requête",
	RequestedFor: "Demandé pour",
	ItemSetID: "ID Ensemble d'articles",
	DateEntered: "Saisi le",
	MRNum: "MRNUM",
	Priority: "Priorité",
	SiteID: "ID site",
	MRLINEID: "ID MRLINE",
	// MyDeploymentsGrid
	MyDeploymentsHeading: "Projets",
	Name: "nom",
	ServiceOwner: "Propriétaire du service",
	StatusDate: "Heure du statut",
	DueDate: "Date d'échéance",
	CreatedDate: "Créé",
	StartDate: "Objectif de démarrage",
	OfferingDescription: "Description de la demande",
	Approval: "Approbation",
	// Catalog Request Creator
	CatalogRequestCreateHeading: "Créer une demande",
	CatalogOfferingPrompt: "Offre du catalogue de service",
	CreateRequestStatus: "La demande a pu être présentée",
	CreateRequestButtonLabel: "OK",
	CancelButtonLabel: "Annuler",
	
	// Navigator widget
	Home: "Accueil",
	Back: "Arrière", 
	Forward: "Avant",
	HomeBreadcrumb: "Accueil",
	Search: "Rechercher",
	SearchResults: "Résultats de la recherche",
	Close: "Fermer",
	IncidentsLabel: "Ouverture d'un ticket d'aide et support",
	IncidentsDesc: "Ouvrir un ticket d'aide pour un actif ou un service existant",
	RequestsLabel: "Demander un nouveau service",
	RequestsDesc: "Ouvrir une demande pour acquérir un nouvel actif ou un nouveau service.",
	RecentsLabel: "Demandes fréquentes",
	RecentsDesc: "Accès rapide aux services les plus souvent demandés.",
	None: "Aucune",
	NA: "N/A",
	//branch in navigator tree
	Directory: "Répertoire",
	//leaf in navigator tree
	Panel: "Panneau",
	// DateRange Widget
	DurationLabel: "Pour cette durée",
	MonthsLabel: "Mois",
	WeeksLabel: "Semaines",
	DaysLabel: "Jours",
	ForeverLabel: "Indéfiniment",
	StartDateLabel: "Date de début",
	EndDateLabel: "Date de fin",
	StartTime: "Horodatage de début",
	EndTime: "Horodatage de fin",
	UntilLabel: "Jusqu'à cette date",
	InvalidDurationMessage: "La durée doit être supérieure à 0",
	InvalidDateMessage: "Ce n'est pas une date valide",
	DateEarlyMessage: "C'est avant ${0}, la première date admissible",
	DateLateMessage: "C'est après ${0}, la dernière date admissible",
	MissingDateMessage: "Cette date doit être obligatoirement indiquée",

	Loading: "Chargement en cours...",
	RecentActivity: "Activité récente",
	NoRecentActivity: "Pas d'activité récente",
	ManageRequests: "Gérer les demandes",
	ManageRequestsLink: "Gérer les demandes...",
	ManageApprovalsLink: "Gérer les approbations...",
	ManageApprovals: "Gérer les approbations",

	//General
	OK : "OK",
	Cancel : "Annuler",
	Select: "Sélection",
	Total: "Total",
	TotalLabel: "Total : ",
	
	// error messages
	MemChunkError: "La mémoire de %1 doit être un multiple de %2 Mo",
	CTJZH2301I: "CTJZH2301I: Désolés, mais aucune correspondance n'a été trouvée.",
	CTJZH2302I: "CTJZH2302I: La connexion a réussi.",
	CTJZH2303I: "CTJZH2303I: Vous n'êtes pas connecté.",
	CTJZH2304I: "CTJZH2304I: Vous devez choisir un serveur virtuel.",
	
	CTJZH2301W: "CTJZH2301W: La récupération de la liste des dates de début utilisables pour votre réservation a échoué.",
	CTJZH2302W: "CTJZH2302W: Le serveur sélectionné comporte déjà une image. La nouvelle image va remplacer l'image existante.",
	
	CTJZH2301E: "CTJZH2301E: Une erreur s'est produite lors de la création du formulaire de saisie pour cette demande.",
	CTJZH2302E: "CTJZH2302E: Une erreur s'est produite lors de la récupération des détails de cette demande.",
	CTJZH2303E: "CTJZH2303E: Pour pouvoir créer une demande, vous devez avoir ouvert une session.",
	CTJZH2304E: "CTJZH2304E: Une erreur s'est produite lors de la création de cette demande.",
	CTJZH2305E: "CTJZH2305E: Des zones de saisie comportent des valeurs non valides.<br>Vous devez corriger ces erreurs pour pouvoir continuer.",
	CTJZH2306E: "CTJZH2306E: Le système a signalé une erreur dans la création de cette demande.",
	CTJZH2307E: "CTJZH2307E: Une erreur s'est produite pendant l'ouverture de session.",
	CTJZH2308E: "CTJZH2308E: Désolé, mais la création de cette demande n'est pas prise en charge à l'heure actuelle.",
	CTJZH2309E: "CTJZH2309E: Une erreur interne m'a empêché de pouvoir continuer.",
	CTJZH2310E: "CTJZH2310E: Echec de l'affichage des détails du projet, impossible de trouver un ID de projet.",
	CTJZH2311E: "CTJZH2311E: Une erreur interne m'a empêché d'afficher les détails du projet.",
	CTJZH2312E: "CTJZH2312E: Une erreur s'est produite lors de la récupération des détails du projet.",
	CTJZH2313E: "CTJZH2313E: La récupération de votre liste de demandes de services a échoué.",
	CTJZH2314E: "CTJZH2314E: Une erreur s'est produite lors de la récupération des détails de ce projet.",
	CTJZH2315E: "CTJZH2315E: La récupération de votre liste de projets a échoué.",
	CTJZH2316E: "CTJZH2316E: Normalement un message devrait s'afficher, mais il est de valeur null, il est indéfini, il comporte du code vide, ou il est de type non valide.",
    //User Management Warnings
	CTJZH2317W: "CTJZH2317W: Le mot de passe de confirmation ne correspond pas !", 
	CTJZH2318W: "CTJZH2318W: Il n'est possible de sélectionner qu'un maximum de cinq équipes !",
	CTJZH2319W: "CTJZH2319W: Le nom d'utilisateur existe déjà !",
	CTJZH2320W: "CTJZH2320W: Il n'est possible de sélectionner qu'un maximum de quinze utilisateurs !",
	CTJZH2321I: "CTJZH2321I: Aucun détail à afficher pour cette demande",
	CTJZH2322W: "CTJZH2322W: Le mot de passe ne peut commencer ni finir par des caractères blancs", 
	
	
	//Approve Request error messages
	CTJZH2321E: "CTJZH2321E: Echec du traitement de la demande que vous avez sélectionnée.",
	
	//String list for user and team
	//Role: "Role",
	//Language: "Language",
	Team: "Equipe",
	UserTeams: "Equipes d'utilisateurs",
	
	//UserStatus: "Activate user account",
	LOGINID: "ID de connexion",
	AccountLegend: "Paramètres du compte",
	PersonalInfoLegend: "Renseignements personnels",
	RegionalSettLegend: "Paramètres régionaux",
	FirstName: "Prénom",
	LastName: "Nom",
	DisplayName: "Nom d'affichage",
	Email: "e-mail",
	Telephone: "Téléphone",
	Address: "Adresse",
	City: "Ville",
	State: "Etat",
	Country: "Pays",
	AccountStatus: "Actif",
	EmptyString: "               ",
	UserList: "Utilisateurs disponibles",
	UserID: "ID Utilisateur",
	Role: "Rôle",
	ConfirmPassword: "Confirmer le mot de passe",
	InvalidConfirmPassword: "Le mot de passe et le mot de passe de confirmation ne concordent pas.",
	PressToAddTeam: "Appuyez sur + pour ajouter une équipe",
	// Team Management
	TeamID: "ID",
	TeamName: "nom",
	TeamDescription: "Description",
	UserList: "Utilisateurs disponibles",
	SelectedUserList: "Utilisateurs sélectionnés",
	TeamDetails: "Détails de l'équipe",
	
	//Project Details
	ProjectTitle: "Projet",
	ProjectDetails: "Détails du projet",
	ProjectDetailsImage: "",
	ProjectName: "Nom du projet",
	ProjectDescription: "Description du projet",
	ProjectType: "Type du projet",
	ProjectStartDate: "Date de début",
	ProjectEndDate: "Date de fin",
	ProjectTeamAccess: "Accès à l'équipe",
	ProjectsDropDownEmptyLabel: "Sélection d'un projet",	
	
	//WCA Projects
	WCAProjectTitle: "Projet WebSphere CloudBurst",
	WCAProjectDetails: "Détails du projet WebSphere CloudBurst",
	WCAProjectPattern: "Nom du pattern",
	WCAServerResourcesLegend: "Ressources",
	WCAServerVirtualCPU: "UC virtuelle",
	WCAServerMemory: "Mémoire principale",
	WCAPatternSelection: "Sélectionnez un pattern CloudBurst",
	
	ServerGridName: "Nom du serveur",
	ServerGridOS: "Syst. d'exploitation",
	ServerGridStatus: "état",
	ServerGridMemory: "Mémoire (en %)",
	ServerGridCPU: "UC (en %)",
	ServerGridDisk: "Disque (en %)",
	ServerGridLastUpdate: "Dernière mise à jour",
	ServerGridHypervisor: "Hyperviseur",
	WCAServerGridPart: "Article",
	ProjectRequestedServers: "Serveur(s) demandé(s)",
	ProjectActiveServers: "Serveur(s) actif(s)",
	
	ViewProjectGeneralLegend: "Général",
	ViewProjectName: "nom",
	ViewProjectDescription: "Description",
	ViewProjectServiceOwner: "Propriétaire du service",
	ViewProjectType: "Type du projet",
	ViewProjectStartDate: "Date de début",
	ViewProjectEndDate: "Date de fin",
	ViewProjectTeamAccess: "Accès à l'équipe",
	ViewProjectRequestedServer: "Serveurs demandés",
	ViewProjectActiveServers: "Serveurs actifs",
	
	ViewProjectServersLegend: "Serveurs",
	ViewProjectServersTitle: "Serveur",
	ViewProjectMasterImage: "Image principale",
	ViewProjectCreateDate: "Date de création",
	ViewProjectCreatedBy: "Créé par",
	ViewProjectHypervisor: "Hyperviseur",
	ViewProjectCPU: "Unité centrale",
	ViewProjectVirtual: "Virtuelle",
	ViewProjectPhysical: "Physique",
	ViewProjectMain: "Principal",
	ViewProjectSwap: "Echanger",
	ViewProjectDisk: "Disque",
	ViewProjectLocal: "Locale",
	ViewProjectAdditionalSoftware: "Logiciels supplémentaires",
	ViewProjectMemory: "Mémoire",
	ViewProjectServersTotal: "Total : ",
	Yes: "Oui",
	No: "Non",
	UserExist: "L'utilisateur existe déjà",
	MaxTeamsExceed: "Excède la longueur maximum de l'équipe",
	PreviewCloseTitle: "Refermer la section",
	PreviewOpenTitle: "Ouvrir la section",

	/* Service Request details */
	Application: "Application",
	CreatedOn: "Créé le",
	Date: "date,",
	Details: "Détails",
	From: "De",
	Subject: "Sujet",
	Summary: "Récapitulatif",
	To: "A",
	ViewSRDetails: "Détails de la demande",
	ViewSRTitle: "Visualiser la demande de service",
	ViewSRGeneral: "Général",
	ViewSRGenBanner: "Cette tâche vous permet d'approuver ou de rejeter une demande de service",
	ViewSRLastUpdate: "Dernière mise à jour",
	ViewSRUpdatedBy: "Mis à jour par ",
	ViewSRWorkLog: "Journal des travaux",
	ViewSRWorkBanner: "Le journal des travaux correspondant à la demande de service. Sélectionnez la ligne pour visualiser les détails de la note.",
	ViewSRNoWorkl: "Aucun journal de travaux à afficher.",
	ViewSRCommLog: "Journal des communications",
	ViewSRCommBanner: "Le journal des communications correspondant à la demande de service. Sélectionnez la ligne pour visualiser les détails de la note.",
	ViewSRNoComml: "Aucun journal de communications à afficher.",
	
	/* Approve Request */
	AppRequestBannerTitle: "Approbation",
	AppRequestBannerDescription: "Une approbation est en attente de votre choix. Quel est votre vote ?",
	RejectRequest: "Je rejette cette demande",
	ApproveRequest: "J'approuve cette demande",
	ApproveSummary: "Récapitulatif",
	ApproveDetails: "Détails",
	
	
	copyright: "Eléments sous licence - Propriété d'IBM Corp. &copy; IBM Corporation and other(s) 2009. IBM est une marque d'IBM Corporation aux Etats-Unis et/ou dans certains autres pays.",
	AboutCopyright: "Eléments sous licence - Propriété d'IBM Corp. &copy; Copyright IBM Corp. 2009. All Rights Reserved. US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contact with IBM Corp.",
	dummy_: ""
}

