({
	"dateFormatItem-yM": "yyyy/M", 
	"field-dayperiod": "قبل/بعد از ظهر", 
	"dateFormatItem-yQ": "yyyy Q", 
	"field-minute": "دقیقه", 
	"eraNames": [
		"قبل از میلاد", 
		"میلادی"
	], 
	"dateFormatItem-MMMEd": "E d LLL", 
	"field-weekday": "روز هفته", 
	"dateFormatItem-yQQQ": "yyyy QQQ", 
	"days-standAlone-wide": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"ژ", 
		"ف", 
		"م", 
		"آ", 
		"م", 
		"ژ", 
		"ژ", 
		"ا", 
		"س", 
		"ا", 
		"ن", 
		"د"
	], 
	"field-era": "دوره", 
	"field-hour": "ساعت", 
	"dateFormatItem-yyyyMMMMEEEEd": "EEEE d MMMM yyyy", 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "H:mm:ss (vvvv)", 
	"months-standAlone-abbr": [
		"ژانویه", 
		"فوریه", 
		"مارس", 
		"آوریل", 
		"مه", 
		"ژوئن", 
		"ژوئیه", 
		"اوت", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"days-standAlone-narrow": [
		"ی", 
		"د", 
		"س", 
		"چ", 
		"پ", 
		"ج", 
		"ش"
	], 
	"eraAbbr": [
		"ق.م.", 
		"م."
	], 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "d MMMM yyyy", 
	"timeFormat-medium": "H:mm:ss", 
	"field-zone": "منطقهٔ زمانی", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "yyyy/M/d", 
	"dateFormatItem-HHmmZ": "HH:mm (Z)", 
	"quarters-standAlone-wide": [
		"سهماههٔ اول", 
		"سهماههٔ دوم", 
		"سهماههٔ سوم", 
		"سهماههٔ چهارم"
	], 
	"dateTimeFormat": "{1}، ساعت {0}", 
	"dateFormatItem-yMMMM": "MMMM yyyy", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "سال", 
	"quarters-standAlone-narrow": [
		"۱", 
		"۲", 
		"۳", 
		"۴"
	], 
	"months-standAlone-wide": [
		"ژانویه", 
		"فوریه", 
		"مارس", 
		"آوریل", 
		"مه", 
		"ژوئن", 
		"ژوئیه", 
		"اوت", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"field-week": "هفته", 
	"dateFormatItem-MMMMEd": "E d LLLL", 
	"dateFormatItem-MMMd": "d LLL", 
	"quarters-format-narrow": [
		"۱", 
		"۲", 
		"۳", 
		"۴"
	], 
	"timeFormat-long": "H:mm:ss (zzzz)", 
	"months-format-abbr": [
		"ژانویهٔ", 
		"فوریهٔ", 
		"مارس", 
		"آوریل", 
		"مهٔ", 
		"ژوئن", 
		"ژوئیهٔ", 
		"اوت", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"timeFormat-short": "H:mm", 
	"field-month": "ماه", 
	"dateFormatItem-MMMMd": "d LLLL", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"pm": "بعد از ظهر", 
	"dateFormatItem-M": "L", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"ی", 
		"د", 
		"س", 
		"چ", 
		"پ", 
		"ج", 
		"ش"
	], 
	"field-second": "ثانیه", 
	"field-day": "روز", 
	"dateFormatItem-MEd": "E M/d", 
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}", 
	"months-format-narrow": [
		"ژ", 
		"ف", 
		"م", 
		"آ", 
		"م", 
		"ژ", 
		"ژ", 
		"ا", 
		"س", 
		"ا", 
		"ن", 
		"د"
	], 
	"am": "قبل از ظهر", 
	"dateFormatItem-GGGGyyyyMMMMd": "d MMMM yyyy GGGG", 
	"days-standAlone-abbr": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"dateFormat-short": "yy/M/d", 
	"dateFormatItem-yyyyM": "yyyy/M", 
	"dateFormatItem-yMMMEd": "E d MMM yyyy", 
	"dateFormat-full": "EEEE d MMMM yyyy GGGG", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "E yyyy/M/d", 
	"months-format-wide": [
		"ژانویهٔ", 
		"فوریهٔ", 
		"مارس", 
		"آوریل", 
		"مهٔ", 
		"ژوئن", 
		"ژوئیهٔ", 
		"اوت", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"سهماههٔ اول", 
		"سهماههٔ دوم", 
		"سهماههٔ سوم", 
		"سهماههٔ چهارم"
	], 
	"days-format-wide": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"eraNarrow": [
		"ق.م.", 
		"م."
	]
})